### ISSUE TITLE
小程序刷新数据怎么不更新图表

### ISSUE THREAD

**Issue by gaomengluo** [antvis/wx-f2#10]
let EchartViewData = res.data.retData.EchartView;
        let xAxisData = res.data.retData.EchartTitle;
        console.log(EchartViewData)
        console.log(chart)
        for (let i = 0; i < EchartViewData.length;i++){
          console.log(i)
          EchartViewData[i]['namex'] = xAxisData[i]
        }
        console.log(EchartViewData)
        chart.source(EchartViewData, {
          value: {
            tickCount: 5,
            min: 0
          },
          namex: {
            range: [0, 1]
          }
        });
        chart.line().position('namex*value').color('value', val => { });
        chart.render();

**Comment by simaQ** [comment]
图表渲染出来之后，需要更新数据的话，直接调用 chart.changeData(data)

**Comment by yaotaiye** [comment]
如果要更新文本呢？
