### ISSUE TITLE
面积图填充颜色有问题

### ISSUE THREAD

**Issue by aloneszjl** [antvis/wx-f2#101]
![image](https://user-images.githubusercontent.com/19307426/45535563-76275e80-b831-11e8-8cce-89f9e541867c.png)

面积图填充的颜色 跟我实际填充的颜色有差距，正确的颜色 应该是跟线的颜色一样才对，请问怎么解决这个问题？

**Comment by simaQ** [comment]
哦哦，这是因为我们的面积图默认的透明度是 0.1, 你只要加一个 `style({ fillOpacity: 1 })` 就可以了。 

```js
chart.area().style({
  fillOpacity: 1
});
```

**Comment by aloneszjl** [comment]
谢谢，我在绘图属性那里并没有找到。
https://antv.alipay.com/zh-cn/f2/3.x/api/geometry.html#_style

**Comment by aloneszjl** [comment]
嗯嗯，感觉这个库很好~
