### ISSUE TITLE
小程序中guide.text fill 渐变色，iOS真机无效，安卓正常

### ISSUE THREAD

**Issue by joeyczz** [antvis/wx-f2#103]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

小程序中guide.text 渐变色，iOS真机无效，安卓正常
`        
         this.guideText = this.chart.guide().text({
          position: ['50%', '60%'],
          content: '4.8',
          style: {
            fill: 'l(90) 0:red 1:white',
            fontSize: '40', // 文本大小
            textBaseline: 'bottom',
            textAlign: 'center'
          },
        });
`
模拟器
![image](https://user-images.githubusercontent.com/15942257/45569676-cc78b980-b892-11e8-81ef-128f94c72b29.png)

iOS真机效果
![image](https://user-images.githubusercontent.com/15942257/45569729-fd58ee80-b892-11e8-9471-dbf648cc3961.png)

**Comment by litaipingcq** [comment]
单独这个自己写要强些

**Comment by simaQ** [comment]
建议自己写。
