### ISSUE TITLE
面积图挡住了折线图

### ISSUE THREAD

**Issue by aloneszjl** [antvis/wx-f2#104]
![image](https://user-images.githubusercontent.com/19307426/45609335-1bd50a80-ba8a-11e8-9c63-5fe990ad0cab.png)
当我想要结合面积图和折线图的时候，如果我使用fillOpacity:1时，发现面积图会覆盖在折线图上面。请问怎么解决这个问题

**Comment by aloneszjl** [comment]
是否有什么办法让线的层级在面积的上面？

**Comment by aloneszjl** [comment]
changeData的时候 有一个警告，但是找不出是哪里有问题，因为数据是同个格式的，只有在changeData的时候才会出现这个警告
![image](https://user-images.githubusercontent.com/19307426/45610827-ec290100-ba8f-11e8-8ce0-6c8e823f7f6a.png)

**Comment by aloneszjl** [comment]
关掉动画就正常了，就不会出现上面那个警告，图也可以正常出来，但是我需要动画

**Comment by simaQ** [comment]
你打印下 F2 的版本，3.2.2 版本这个问题我应该修复了的

**Comment by simaQ** [comment]
F2.version

**Comment by aloneszjl** [comment]
3.2.2-beta.3

**Comment by simaQ** [comment]
关注一下 @antv/f2 的 changelog，建议使用最新稳定版本。 3.2.2，我已经更新到 f2-canvas/lib/f2.js 了，你更新下看看

**Comment by aloneszjl** [comment]
好的，我明天试试。谢谢你。这个库非常棒！！！
这么好的库，我有空也会看下issue，帮忙解答问题，支持支持。

**Comment by aloneszjl** [comment]
https://github.com/antvis/wx-f2/tree/master/f2-canvas/lib
找不到啊...好像被你删掉了
![image](https://user-images.githubusercontent.com/19307426/45623527-3de68100-baba-11e8-9054-31a33f928b6f.png)

**Comment by aloneszjl** [comment]
![image](https://user-images.githubusercontent.com/19307426/45623571-640c2100-baba-11e8-9b07-045cb9182aef.png)

**Comment by simaQ** [comment]
哦，不小心删了，但是你可以自己按照 ReadMe 说的去 @antv/f2 自己拿呀

**Comment by simaQ** [comment]
上传了，无语了，怎么会误删...
