### ISSUE TITLE
【bug】在taro中引入f2报错

### ISSUE THREAD

**Issue by teapot-py** [antvis/wx-f2#109]
按着官方文档的方式在taro中引入了f2,但是报错了:
![image](https://user-images.githubusercontent.com/10125102/45870115-bc923580-bdbc-11e8-85fb-7cff86ca9f95.png)

**Comment by simaQ** [comment]
报这个错的原因是 canvas 的 width 和 height 没有取到，你检查下 width 和 height 的值

**Comment by huxiao123** [comment]
如果不设置width和height就会报错，设置了又没有什么效果～尴尬啊[
<img width="987" alt="2018-09-25 3 14 11" src="https://user-images.githubusercontent.com/13741654/45998582-df329000-c0d5-11e8-869f-142b11ddf4b2.png">
](url)

**Comment by huxiao123** [comment]
我需要在js文件里面，单独初始化一下opts: {
      onInit: initChart
    }这个方法，给他传入canvas和width，height？？？？？？？

**Comment by simaQ** [comment]
额，我不熟悉 taro 框架，你可以尝试下，报这个错的原因基本就是 width 和 height 没有拿到，或者 canvas 元素还没有初始化成功

**Comment by huxiao123** [comment]
> 额，我不熟悉 taro 框架，你可以尝试下，报这个错的原因基本就是 width 和 height 没有拿到，或者 canvas 元素还没有初始化成功

小姐姐～问一下，我需要单独给initChart传入canvas和width，height？？？？？？？

**Comment by simaQ** [comment]
或者你检查下 .wxss 文件中是否定义了 ff-canvas 的样式：https://github.com/antvis/wx-f2/blob/master/app.wxss#L16

**Comment by huxiao123** [comment]
> 或者你检查下 .wxss 文件中是否定义了 ff-canvas 的样式：https://github.com/antvis/wx-f2/blob/master/app.wxss#L16

确实是没有引入样式，造成的报错～～～～
