### ISSUE TITLE
这个怎么赋值啊？

### ISSUE THREAD

**Issue by churjan** [antvis/wx-f2#114]
文档里面没写,不能通过传参数的形式赋值，不能在里面调用this.data里面的值

**Comment by simaQ** [comment]
what?!

**Comment by churjan** [comment]
那个wx-f2你开放的吗？我最近在做一个项目要用到这个组件，但是引用的时候有很多问题，能不能加个联系方式，有偿回答。




| |
邱健
邮箱：churjan@163.com
|

签名由 网易邮箱大师 定制

在2018年09月27日 10:53，SimaQ 写道：

what?!

**Comment by simaQ** [comment]
开源的，具体的问题，你通过 issue 提出吧，描述好场景，提示的错误信息以及可复现的代码。

**Comment by simaQ** [comment]
区域图的话，直接将 chart.line() 改成 chart.area() 就变成面积图了呢，可以参考 https://antv.alipay.com/zh-cn/f2/3.x/demo/area/basic.html 这个 demo

**Comment by ldwonday** [comment]
怎么通过this传值啊，都是写死的data！@churjan
