### ISSUE TITLE
平移交互时，X轴部分数据不显示

### ISSUE THREAD

**Issue by ymsh** [antvis/wx-f2#120]
* **F2 Version**: 3.2.3 beta5
* **Platform**: 微信小程序
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![75b94533-0fa8-4e5f-a2a5-1d48ffaa8341](https://user-images.githubusercontent.com/20986849/46356570-96f70d00-c695-11e8-9611-86807cfc7941.png)
![4237e3b1-af3f-4598-86ef-f46aa73b72a4](https://user-images.githubusercontent.com/20986849/46356597-a4ac9280-c695-11e8-8306-27d8e256417f.png)

上图是显示一天24小时的柱状数据，
设置了字段
hour: {
      min: '05',
      max: '23'
    }

后，滚动条是出现了，但数据也只显示05到23小时，怎么设置才能让00到05小时的数据也显示出来？？

**Comment by simaQ** [comment]
你好，因为你的 x 轴（对应 hour 字段）的数据是分类类型，这种情况下不应该是用 min 和 max 属性设置数据展示的范围，应该使用 values 字段：

```js
chart.scale({
  hour: {
    values: [ '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24' ]
  }
});
```

**Comment by ymsh** [comment]
谢谢指教，问题解决
