### ISSUE TITLE
柱状图如何限制Y轴上最小值为0

### ISSUE THREAD

**Issue by churjan** [antvis/wx-f2#124]
![image](https://user-images.githubusercontent.com/15041918/47192962-03a32480-d383-11e8-8ffc-caf4afd5b000.png)
差文档可以同过设置min来设置，但没有生效
![image](https://user-images.githubusercontent.com/15041918/47192921-c0e14c80-d382-11e8-86d1-a2df65448b56.png)

还有每个值之间最小间隙是1，即不显示小数点，这个插件可以实现吗？
![image](https://user-images.githubusercontent.com/15041918/47192986-29c8c480-d383-11e8-84b4-f84045eeaa26.png)

**Comment by simaQ** [comment]
首先纠正一下，这个是面积图。有两个方法可以设置：

1. 直接设置 ticks 属性，自己决定展示的坐标轴文本内容
```js
ticks: [ 0, 2, 4, 6, 8, 10 ]
```

2. 设置 min 之后，再设置 tickInterval，即刻度之间的间隔

```js
min: 0,
tickInterval: 2
```
