### ISSUE TITLE
请问如何改造使之适用于百度智能小程序？

### ISSUE THREAD

**Issue by mimipigs** [antvis/wx-f2#126]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

请问如何改造使之适用于百度智能小程序？

**Comment by simaQ** [comment]
具体的改造方法详见：https://www.yuque.com/antv/blog/bg9sxf

**Comment by simaQ** [comment]
具体改造方法可以参考：https://www.yuque.com/antv/blog/bg9sxf

**Comment by mimipigs** [comment]
感谢回复，该篇文章上周研究过啦。且依葫芦画瓢，进行了改造，但水平有限，最终没能成功。
