### ISSUE TITLE
辅助线在真机上不显示

### ISSUE THREAD

**Issue by gaojing007** [antvis/wx-f2#128]
Antv-F2图表示例小程序里面的实例：双Y轴。平均降雨量的辅助线不显示。

**Comment by simaQ** [comment]
辅助线在样式上是不是使用了 lineDash 属性？部分机型对这个属性是不兼容的

**Comment by gaojing007** [comment]
补充下：安卓的手机不显示。

**Comment by gaojing007** [comment]
代码是你的github上double-axis实例

**Comment by gaojing007** [comment]
的确是lineDash的问题
