### ISSUE TITLE
npm中有@antv/wx-f2 和 @antv/f2-canvas，该使用哪个？

### ISSUE THREAD

**Issue by Jony1943** [antvis/wx-f2#129]
我看到npm中有@antv/wx-f2 和 @antv/f2-canvas，两个有什么差别吗？

* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
在 readme 中已经说明了，使用 @antv/f2-canvas, 它是 F2 的微信小程序图表自定义组件。按照例子来就行了，@antv/wx-f2 是 F2 对于微信小程序进行的适配。
