### ISSUE TITLE
Yaxis刻度异常

### ISSUE THREAD

**Issue by Gray497** [antvis/wx-f2#13]
![image](https://user-images.githubusercontent.com/20183400/41400927-0333b94c-6ff1-11e8-9514-7d7bd311b489.png)

刻度理应是升序，但图中左侧刻度29.7->29.1->29.6此行为为异常

**Comment by simaQ** [comment]
你的 Y 轴数据是不是数据字符串，类似于 '29.7' ?  F2 对数据是强类型定义的，需要将其转换成 29.7 这样的

**Comment by Gray497** [comment]
@simaQ 好的，问题已经解决了，谢谢
