### ISSUE TITLE
小程序怎么动态设置数据，不要告诉我说去看K线的东西，那个报错的

### ISSUE THREAD

**Issue by imBigbaibai** [antvis/wx-f2#133]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
并没有报错，就是参考 K 线图例子，异步更新数据。

**Comment by espring** [comment]
K线例子里, 是用init 函数重画的, 请问有没有用changeData的例子? 谢谢.
