### ISSUE TITLE
Xaxis底部的小白线能去掉的吗？

### ISSUE THREAD

**Issue by Gray497** [antvis/wx-f2#14]
![image](https://user-images.githubusercontent.com/20183400/41403443-790820a8-6ff7-11e8-9ddf-a9860577f29d.png)

**Comment by simaQ** [comment]
可以的。chart.axis('x 轴对应字段的名称', { line: null })

**Comment by Gray497** [comment]
@simaQ 小姐姐，chart.axis('time', { line: null, grid: false }) 我这样试了没啥改变，是我搞错了吗
