### ISSUE TITLE
wepy  这个框架直接可以npm install wx-f2吗？

### ISSUE THREAD

**Issue by iwen-pengh** [antvis/wx-f2#140]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by iwen-pengh** [comment]
wepy 如何使用这个框架

**Comment by simaQ** [comment]
wx-f2 是针对微信小程序原生环境封装的，并没有为 wepy 这个框架作支持。

**Comment by iwen-pengh** [comment]
好吧 # @simaQ
