### ISSUE TITLE
乱！！！

### ISSUE THREAD

**Issue by hackgyj** [antvis/wx-f2#142]
***乱***
一个F2微信小程序版本讲到了三个包地址：``wx-f2``，``f2-canvas``，``wx-f2/tree/custom-components``。
虽然仔细看懂关联性了，但搞这么复杂好吗，官方是否可以整理一下，弄成一个包，然后把使用方法合并整理一下？？？不用三个地址来回跑？？？

> npm使用方法
> 原生组件使用用法

其它直接看F2文档就好

### 如此好用的F2被管理这么随意的对待！

**Comment by simaQ** [comment]
已经在 readme 说明清楚，npm 模块引入方式你只要引入 f2-canvas 即可，并不需要关心其他模块。
