### ISSUE TITLE
微信小程序中引入PieLabel报错

### ISSUE THREAD

**Issue by yangguangfan** [antvis/wx-f2#144]
![lalpdgq9qxny_8xnainna6c_935_553](https://user-images.githubusercontent.com/45507119/49325221-971e6680-f579-11e8-9e70-ad4cbd411523.png)
使用该方法无法再小程序中引入，请问是什么问题，我该怎样引入这个插件

**Comment by simaQ** [comment]
你使用的是 npm 模块还是之前自定义组件的方式引入的？  

如果是 npm 模块引入的话，我这边需要升级下版本依赖。
如果是自定义组件的方式引入，自己 download 下 https://unpkg.com/@antv/f2@3.3.1/dist/f2-all.min.js 就好

**Comment by yangguangfan** [comment]
我现在使用的是npm模块

**Comment by simaQ** [comment]
https://github.com/antvis/wx-f2/blob/master/package.json#L7 升级下依赖的版本

**Comment by CarisL** [comment]
> 你使用的是 npm 模块还是之前自定义组件的方式引入的？
> 
> 如果是 npm 模块引入的话，我这边需要升级下版本依赖。
> 如果是自定义组件的方式引入，自己 download 下 https://unpkg.com/@antv/f2@3.3.1/dist/f2-all.min.js 就好

这个会报下面的错误
![image](https://user-images.githubusercontent.com/13416424/74017931-ff63a600-49cf-11ea-978c-34eedb68addb.png)

**Comment by babizhu** [comment]
解决了吗？

**Comment by gong12339** [comment]
+1，遇到了同样的问题，替换min.js后也报createElement of undefined错误

**Comment by li305263** [comment]
+1，遇到了同样的问题，替换min.js后也报createElement of undefined错误 
3.31版本也不行啊引入也报错
