### ISSUE TITLE
折线图，Y轴的数据不是按照大小排序的，

### ISSUE THREAD

**Issue by imBigbaibai** [antvis/wx-f2#149]
数据返回正常，但是 y轴不是按照大小排序的，求解答一下，

**Comment by simaQ** [comment]
检查下你的 y 轴对应的数据是不是数字类型，按照你这简单的描述，推测应该是字符串数字类型，比如 '12'，你需要将它转换为纯数字类型。

**Comment by imBigbaibai** [comment]
> 检查下你的 y 轴对应的数据是不是数字类型，按照你这简单的描述，推测应该是字符串数字类型，比如 '12'，你需要将它转换为纯数字类型。

嗯，对，服务器返回我是 "13.22"字符串，多谢，我让服务器改成纯数字类型double, 字符串类型我设置ticks是不生效的吗？

**Comment by simaQ** [comment]
> > 检查下你的 y 轴对应的数据是不是数字类型，按照你这简单的描述，推测应该是字符串数字类型，比如 '12'，你需要将它转换为纯数字类型。
> 
> 嗯，对，服务器返回我是 "13.22"字符串，多谢，我让服务器改成纯数字类型double, 字符串类型我设置ticks是不生效的吗？

是生效的，把类型改成数字类型就好了。
