### ISSUE TITLE
tooltips的title内容可以自定义吗？

### ISSUE THREAD

**Issue by Gray497** [antvis/wx-f2#15]

**Comment by simaQ** [comment]
恩，可以的。api: https://antv.alipay.com/zh-cn/f2/3.x/api/tooltip.html#_API 

使用 onShow 或者 onChange 的钩子，demo: https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/basic-column.html

**Comment by Gray497** [comment]
![image](https://user-images.githubusercontent.com/20183400/41448335-a98fb2aa-708c-11e8-87c6-a88a26fb56af.png)

小姐姐我想改的是这个

**Comment by simaQ** [comment]
啊哈哈，我非常喜欢你这个『小姐姐』的称呼: titleStyle 属性

```js
chart.tooltip({
  titleStyle: {
    fontSize: 24, 
    fill: '#fff', // 字体颜色
    textAlign: 'start',
    textBaseline: 'top'
  }, // tooltip 标题的文本样式配置，showTitle 为 false 时不生效
})
```

**Comment by Gray497** [comment]
@simaQ nice 小姐姐太厉害了，我的心都被你勾走了

**Comment by youngjuning** [comment]
你俩太好玩了
