### ISSUE TITLE
为何我找不到 wx-f2 的开源代码

### ISSUE THREAD

**Issue by DiamondYuan** [antvis/wx-f2#153]
npm 上的 wx-f2 而不是现在这个 demo 项目。

**Comment by simaQ** [comment]
https://github.com/simaQ/wx-f2 

这个项目只是实例。

**Comment by DiamondYuan** [comment]
> https://github.com/simaQ/wx-f2
> 
> 这个项目只是实例。

非常感谢。希望能在 package.json 里标记一下。

https://github.com/simaQ/wx-f2/blob/297e06f22c6f7670cfafccd6c42507d34310155a/package.json#L10

**Comment by simaQ** [comment]
恩， 好的
