### ISSUE TITLE
微信小程序中 雷达图 如何控制网格的半径大小

### ISSUE THREAD

**Issue by lirong098** [antvis/wx-f2#154]
如下图
![image](https://user-images.githubusercontent.com/20551185/50393029-55ef3000-078e-11e9-8d1c-bf3050570b91.png)
看文档找到设置半径的参数
chart.coord('polar', {
    radius: 1
});
可是最大只能设1。
请问有什么方法吗？

**Comment by simaQ** [comment]
radius 的值只能是是 0 - 1 范围内的，是相对设置的。如果你想要将雷达图放大的话，可以设置下 padding 以及 appendPadding

**Comment by lirong098** [comment]
![image](https://user-images.githubusercontent.com/20551185/50413542-cfe4ef00-084a-11e9-9d73-e62168920657.png)
@simaQ 非常感谢
