### ISSUE TITLE
f2 不能够设置title的吗？

### ISSUE THREAD

**Issue by zcanjie** [antvis/wx-f2#16]

**Comment by Gray497** [comment]
希望能帮到你


onShow: function onShow(ev) {
      var items = ev.items;
      items[0].title = items[0].origin.time;
      items[0].name = null;
      items[0].value = '温度：' + items[0].value;
      items[1].name = null;
      items[1].value = '湿度：' + items[1].value;
    },

**Comment by zcanjie** [comment]
这个好像不是设置曲线图的title的吧。看起来应该是页面的title的。。在官方教程里面，也是没有找到f2 配置title 的相关资料，搜出来的教程是 G2 的

**Comment by zcanjie** [comment]
![image](https://user-images.githubusercontent.com/11417549/41571875-d44d103c-73a7-11e8-8388-56700be8fce0.png)

比如这种的，要在y轴配置一个 title = 销售额 这个，只能自己加一个view或者text 自己来配上去，但是在真机上，体验不是很好，真机上 canvas 默认被置顶了，加的 view或者 text 和 canvas 不是一个层级的

**Comment by Gray497** [comment]
那我就没用过了

**Comment by zcanjie** [comment]
试下看看， thanks~

**Comment by Rabbitzzc** [comment]
> 目前坐标轴不支持 title...
> 这种情况可以使用 chart.guide.text()。
> 
> DEMO：https://codepen.io/Sima/pen/QxaOBK

那这块后续会加上标题么？？两年了
