### ISSUE TITLE
微信小程序 真机调试 平移动x轴滚动条 会报错 如下。 是否是个bug? 还是使用方式不对？

### ISSUE THREAD

**Issue by leeyongda** [antvis/wx-f2#167]
Cannot read property '0' of undefined;at pages/index page $F2Canvas$touchMove function
TypeError: Cannot read property '0' of undefined

**Comment by leeyongda** [comment]
已解决

**Comment by xianxingzhe** [comment]
> 已解决


请教下这个问题是怎么解决的

**Comment by SimoralX** [comment]
> 已解决

同问，请问怎么解决的？
