### ISSUE TITLE
axis (x轴）label 属性，设置textAlign=end 在真机的效果等同于start。。。。

### ISSUE THREAD

**Issue by zcanjie** [antvis/wx-f2#17]
测试环境: 
ios11.3
小程序基础库: 2.1.0  

// x 轴
  chart.axis('year', {
    // 第一个点左对齐，最后一个点右对齐，其余居中，只有一个点时左对齐
    label: (text, index, total) => {
      const cfg = {
        textAlign: 'center'
      };
      if (index == 0) {
        cfg.textAlign = 'start';
      }
      if (index > 0 && index == total - 1) {
        cfg.textAlign = 'end';
      }
      cfg.fill = '#fff';
      return cfg;
    },
    line: {
      lineWidth: 0.7,
      stroke: '#ededed'
    },
    labelOffset: 10,
  })
axis (x轴）label 属性，设置textAlign=end 在真机的效果是start的效果。。。。

**Comment by simaQ** [comment]
使用 left、right 看看。

**Comment by zcanjie** [comment]
使用right 可以了~ 谢谢
