### ISSUE TITLE
同一页面怎么创建多个折线图呢？

### ISSUE THREAD

**Issue by jeanboydev** [antvis/wx-f2#172]
例如在微信小程序的一个页面中创建多个折线图，Demo 和文档中都是创建一个折线图，没有找到创建多个折线图的方式，还请解答下，谢谢！

**Comment by simaQ** [comment]
https://github.com/antvis/wx-f2/tree/master/pages/charts/multiCharts

**Comment by jeanboydev** [comment]
多谢 @simaQ

**Comment by yaoboGit** [comment]
好难受，怎么给出的链接都失效了

**Comment by zengyue** [comment]
用最新版的，填加多标签就可以了，具体使用看readme

**Comment by mk965** [comment]
> 用最新版的，添加多标签就可以了，具体使用看readme

多标签会相互影响，请问如何解决
