### ISSUE TITLE
在ios系统微信小程序中f2 canvas上下滚动页面无效。

### ISSUE THREAD

**Issue by ChunrunHan** [antvis/wx-f2#181]
![image](https://user-images.githubusercontent.com/25897358/55301072-44908080-546d-11e9-997b-2c8e0c980341.png)
微信小程序ios系统中f2 canvas按住滚动页面卡住问题
在Android系统按住canvas 上下滚动页面没问题，
在ios系统微信小程序中按住canvas 上下滚动页面无效。

**Comment by shuzhiweb** [comment]
兄弟，同样的问题，请问你解决了吗

**Comment by ddosakura** [comment]
> 兄弟，同样的问题，请问你解决了吗

滚动卡死可能是因为把图表组件放在了scroll-view里，不使用scroll-view正常滑动似乎不会有问题，但是在iOS下，上拉触底的时候还是有问题——[#208](https://github.com/antvis/wx-f2/issues/208)

**Comment by hexiaojun5233** [comment]
> ![image](https://user-images.githubusercontent.com/25897358/55301072-44908080-546d-11e9-997b-2c8e0c980341.png)
> 微信小程序ios系统中f2 canvas按住滚动页面卡住问题
> 在Android系统按住canvas 上下滚动页面没问题，
> 在ios系统微信小程序中按住canvas 上下滚动页面无效。
请问你那边解决了吗 我这边遇上了同样的问题
