### ISSUE TITLE
如何渲染接口返回的数据

### ISSUE THREAD

**Issue by lishaoh** [antvis/wx-f2#19]
let data = [];

function initChart(canvas, width, height) {
    // console.warn(canvas);
    // console.warn(width)
    // var ctx = wx.createCanvasContext('feature-line', this);
    // const canvas = new Renderer(ctx);
    // const query = wx.createSelectorQuery().in(this);
    // console.info(query)
    // query.select('.feature-line-dom').boundingClientRect(res => {
    //         console.warn(res)
    //     })
    // console.info(canvas)

    chart = new F2.Chart({
        el: canvas,
        width,
        height
    });

    chart.source(data, {
        value: {
            tickCount: 5,
            min: 0
        },
        day: {
            range: [0, 1]
        }
    });
}
Page({
    data: {
        opts: {
            onInit: initChart
        }
    },
    onShow: function() {
        const that = this;
        app.cRequest({
            url: 'body-data',
            success: function(res) {
                if (res) {
                    that.setData(res);
                   
                }
            }
        })
    },
})

**Comment by lishaoh** [comment]
data数据是接口返回的数据

**Comment by simaQ** [comment]
https://github.com/antvis/wx-f2/tree/master/pages/charts/k  参考这个例子，异步返回数据

**Comment by yaoboGit** [comment]
@simaQ  https://github.com/antvis/wx-f2/tree/master/pages/charts/k 链接打不开？
