### ISSUE TITLE
请教一下页面多图表的定位问题

### ISSUE THREAD

**Issue by Lninn** [antvis/wx-f2#197]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

### 简单描述问题：
如图所示，页面中所有的图表是放在 scroll-view 中的，想实现通过点击页面顶部的按钮，调到对应的图表去。在模拟器上没有出现问题，可以通过按钮跳转到对应的图表ID，也可以上下滑动；在真机上演示的时候，滑动没有问题，当点击按钮的时候，页面的元素不受控制，会出现图表绘制错误或不绘制。主要是想通过 scroll-view 的 scroll-into-view 实现锚点定位。

### 预期效果：
![img1.jpg](https://i.loli.net/2019/07/13/5d29df14a6f0032640.jpg)

### 实际效果：
![img2.jpg](https://i.loli.net/2019/07/13/5d29df725c32528681.jpg)

**Comment by Lninn** [comment]
后来发现是样式问题，又自己解决了

**Comment by gongzhw** [comment]
> 后来发现是样式问题，又自己解决了

请问一个页面如何放多个图表 初始化的啊
