### ISSUE TITLE
tooltip 在真机上只能点一次 然后就失效了

### ISSUE THREAD

**Issue by YLPeng** [antvis/wx-f2#202]
在 模拟器上操作没有任何问题， 放到真机上 tooltip 点过一次之后就不好用了。

debug试了以下方法
`chart.tooltip({
                    onShow: function onShow(ev) {
                        console.log('[tooltip] on show', ev)
                    }
                });`
在模拟器上 每点一下图表都会触发 onShow

在真机上跑， 只有点第一下时 有onShow的log

可能是图层顺序问题？

**Comment by liangxinwei** [comment]
同问

**Comment by Pang-Shuai** [comment]
我也遇到同样问题

**Comment by yumengbdw** [comment]
同问

**Comment by YLPeng** [comment]
换包吧 兄弟们， f2 一点答复都不给

**Comment by yumengbdw** [comment]
我外面包了一层scrollview,去掉了就好了,应该是在android机子上面手势冲突

**Comment by yumengbdw** [comment]
> 我外面包了一层scrollview,去掉了就好了,应该是在android机子上面手势冲突



> 我外面包了一层scrollview,去掉了就好了,应该是在android机子上面手势冲突

@YLPeng @liangxinwei @Pang-Shuai

**Comment by Pang-Shuai** [comment]
@yumengbdw 我并没有在外面写scrollview，我是多图表，会有影响吗

**Comment by yumengbdw** [comment]
> @yumengbdw 我并没有在外面写scrollview，我是多图表，会有影响吗

我也是多表,三个tab 每个tab两张图.
