### ISSUE TITLE
微信canvas支持2d啦，f2适配一波吗？非常期待！

### ISSUE THREAD

**Issue by gengyusheng** [antvis/wx-f2#211]
期望f2可以适配微信小程序canvas 2d，嘻嘻。

**Comment by JeKing** [comment]
这个官方计划啥时候兼容呢？

**Comment by gengyusheng** [comment]
> 这个官方计划啥时候兼容呢？

其实现在改改貌似也能用。但是绘制模糊，还有点别的问题，没深入研究。期待官方适配。
