### ISSUE TITLE
thirdScriptError Cannot read property 'defaultView' of undefined;at SelectorQuery callback function 

### ISSUE THREAD

**Issue by yumengbdw** [antvis/wx-f2#213]
thirdScriptError Cannot read property 'defaultView' of undefined;at SelectorQuery callback function 

多个tab下面,每个tab都有多个折线图,只有显示激活状态的tab下的图形显示正常,其他tab的图形均无法显示.并报以上错误

    "@antv/f2-canvas": "^1.0.5",

**Comment by cindyuan** [comment]
同遇到这个问题。。。

**Comment by lgming** [comment]
@yumengbdw 需要指定container的宽高，参考以下：
.container {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;

  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
  box-sizing: border-box;
}
