### ISSUE TITLE
微信小程序 tooltip 不显示

### ISSUE THREAD

**Issue by soonfy** [antvis/wx-f2#22]
微信开发者工具直接打开 wx-f2 项目，可以使用 tooltip；

我在 mpvue 中使用，引入 wx-f2 项目中的 f2-canvas，改成手动初始化渲染
```js
opts: {
  lazyLoad: true
}
this.$mp.page.selectComponent('#canvas').init(initChart)
```

图形已经渲染，tooltip 没效果，是因为我引入的 f2-canvas 不是完整版的，没有 tooltip 插件？还是由于我哪里使用错误？

**Comment by simaQ** [comment]
f2-canvas 内的 f2.js 是完整的。 tooltip 是有图表组件的 touch 事件触发的，可以看这里 https://github.com/antvis/wx-f2/blob/master/f2-canvas/f2-canvas.js#L97，没有渲染出来的话，可能是事件绑定没有成功

**Comment by soonfy** [comment]
@simaQ 

> 我用的 charts/line 做测试，没有修改配置

```js
chart.tooltip({
  custom: true,
  showCrosshairs: true,
  onChange(obj) {
    console.log(obj)    // 打印
    const legend = chart.get('legendController').legends.top[0]
    const tooltipItems = obj.items
    const legendItems = legend.items
    const map = {}
    legendItems.map(item => {
      map[item.name] = Object.assign({}, item)
    })
    tooltipItems.map(item => {
      const { name, value } = item
      if (map[name]) {
        map[name].value = value
      }
    })
    legend.setItems(Object.values(map))
  },
  onHide() {
    const legend = chart.get('legendController').legends.top[0]
    legend.setItems(chart.getLegendItems().country)
  }
})
```

> wxml

![image](https://user-images.githubusercontent.com/14900474/41701425-0c523d50-755f-11e8-9479-53232a61e2f6.png)

onChange 监听事件没有打印数据。
还需要配置什么嘛？

**Comment by simaQ** [comment]
那应该是事件没有监听成功，不需要什么配置的。我没有用过  mpvue  耶，环境还不一样么？

**Comment by simaQ** [comment]
![image](https://user-images.githubusercontent.com/6628666/41701981-0a8efa7e-7561-11e8-90f7-02e8b52825e7.png)

这个截图是完整的么？ touchStart 是不是少了个 t

**Comment by soonfy** [comment]
嗯，是截图没显示出来。

![image](https://user-images.githubusercontent.com/14900474/41702236-fa421fb0-7561-11e8-864b-a1f46efbb019.png)

**Comment by padma0** [comment]
遇到同样的问题，调试发现有触发f2-canvas的touchMove，touchStart等事件

**Comment by simaQ** [comment]
mpvue 上使用的话，是不是也可以使用微信开发者工具打开？如果可以的话，可否提供一个可直接运行的项目包给偶，偶本地调试下看看是什么问题。

**Comment by soonfy** [comment]
@simaQ 

测试项目地址  https://github.com/soonfy/wx-mini

1. clone
2. npm i
3. npm run dev
4. 微信开发者工具打开 wx-mini 文件夹

**Comment by simaQ** [comment]
哦，my god，这个我无能为力了，可以请教下 myvux 社区的人，touchstart 事件是触发了，但是不确定是不是事件监听器有没有注册成功，调试不进去。

**Comment by 969723815** [comment]
这个问题解决了嘛，我也用mpvue时候遇到了

**Comment by F-loat** [comment]
加个 v-if="canvasId" 判断下

**Comment by wdz930** [comment]
大佬们  这个问题解决了没  我也遇到了

**Comment by soonfy** [comment]
@F-loat “vue 的初始化会比页面稍晚一点”
v-if 判断是加在哪里？html部分？还是methods部分？
这个判断的意图是什么？

**Comment by F-loat** [comment]
加在模板里，具体原因我也不是太清楚，但是不加的话，在真机里 canvas 的触摸事件会变成和普通元素一样的，导致各种问题

**Comment by soonfy** [comment]
@F-loat 不好意思，我不太理解 `v-if="canvasId"` 是什么意思。

`v-if` 不是应该传一个变量？而 `canvasId` 是一个字符串

```html
<div class="chart-wrap">
  <ff-canvas v-if="canvasId" id="canvas" canvas-id="canvasId" :opts="opts"/>
</div>
```

模版这块该怎么写？

**Comment by F-loat** [comment]
你没有接触过 vue 吗，data 里有 canvasId 这个变量后，v-if 中直接调用就可以

**Comment by soonfy** [comment]
@F-loat 我想表达的问题是，这个变量 `canvasId` 指向哪里？赋什么值？单纯赋值 `true` 还是没办法显示 tooltip。

**Comment by F-loat** [comment]
这就是个 id 啊，字符串，用来保证 vue 实例创建后再渲染 canvas

**Comment by soonfy** [comment]
@F-loat 你说的是这样嘛？

```html
<div class="chart-wrap">
  <ff-canvas v-if="canvasId" id="canvas" canvas-id="canvasId" :opts="opts"/>
</div>
```

```js
data() {
  return  {
    canvasId: 'canvasId'
  }
}
```

这样还是没办法触发 tooltip 。

**Comment by F-loat** [comment]
你测试下触摸事件正常不，这个库的 tooltip 我不太清楚

**Comment by 969723815** [comment]
这个我之前试过，触发啥的都正常，就是不出来tooltip

**Comment by soonfy** [comment]
@F-loat 

```html
<div class="chart-wrap">
  <ff-canvas v-if="canvasId" id="canvas" canvas-id="canvasId" 
  :opts="opts" @touchstart="touchstart" />
</div>
```
直接绑定的 touchstart 事件可以触发。

.
.
.

另外，我打印了 wx-f2 配合使用 mpvue 的 canvas 对象

![image](https://user-images.githubusercontent.com/14900474/43559634-5fb852e2-9641-11e8-84f7-1a2ad3be8f1d.png)

和直接使用 wx-f2 的 canvas 对象

![image](https://user-images.githubusercontent.com/14900474/43559623-51ee772c-9641-11e8-9b39-0ff554144da2.png)

发现，原生模式下 canvas 对象绑定了 touch 相关的事件， mpvue 模式下 canvas 对象却没有，是不是和这个有关？

**Comment by F-loat** [comment]
你可以看下我的 mpvue-echarts 那个库，触摸事件就是通过加了 v-if 解决的

**Comment by soonfy** [comment]
@F-loat 加了 `v-if` 之后，事件绑定上了，但是值都是空数组。还有什么需要注意的嘛？

![image](https://user-images.githubusercontent.com/14900474/43570315-9274f4d0-966c-11e8-9efa-bd96a4f78ecd.png)

原生的会有监听相关的属性

![image](https://user-images.githubusercontent.com/14900474/43570574-3e533a50-966d-11e8-80d1-aaeed62fdd3d.png)

.
.
.

刚开始我是用 mpvue-echarts 的，当时没有 tooltip，另外我不知道用的方式不对还是怎样，数据加载完成后图形渲染得 1-2 秒。

**Comment by soonfy** [comment]
@simaQ 我在 touchstart 注册事件位置，打印出来 event 是有数据的

![image](https://user-images.githubusercontent.com/14900474/43571237-09024a60-966f-11e8-8595-319401b13954.png)

![image](https://user-images.githubusercontent.com/14900474/43571245-106a1c42-966f-11e8-817e-e06ca399aca1.png)

是因为没监听到事件嘛？还是没发送事件嘛？

**Comment by simaQ** [comment]
之前我尝试的时候，是有捕捉到数据的，但是我搞不懂为什么 F2 的事件机制没有接收到。。。 对 mp-vue 不太了解呢。。。

**Comment by F-loat** [comment]
我那个项目是不加 v-if 的话也可以获取到触摸事件，但是获取到的是普通元素的触摸事件，canvas 元素的事件应该是不一样的，所以会有问题

**Comment by secreter** [comment]
mark

**Comment by EngMJ** [comment]
@soonfy 然后你搞定了不？

**Comment by LucaLJX** [comment]
@F-loat 我是在最新的mpvue-entry quickStart模版里面使用，报下面的错误，你们都没碰到吗？
看了一下源码，是f2.js里面的报错

![_20180911160259](https://user-images.githubusercontent.com/16076854/45346600-30be2380-b5dc-11e8-8fbd-a7dcec4edbae.png)

**Comment by LucaLJX** [comment]
wx-f2在mpvue使用懒加载成功加载了，但是tooltip使用了@F-loat的方法还是不行，打印touch事件，start、move、end事件全都进去了，但是图标没有的tooltip没有对应的效果响应，各位有谁解决了麻烦贴一下方案啊

**Comment by EngMJ** [comment]
搞了一下，弄了个折中办法。就是直接写原生小程序组件，然后在mpvue的页面去引用。就像用那些原生UI组件库一样就ok了。  现在已经不相信什么多端神话。上手一时爽，重构火葬场！

**Comment by LucaLJX** [comment]
@EngMJ 所有的数据逻辑都在原生里面写，vue不作任何数据处理么？

**Comment by EngMJ** [comment]
都在里面写也没什么毛病。  然后设置一个原生的props，在mpvue页面照样传数据就行了。   手头没电脑，有需要的话明天给你截个图。

**Comment by ywzhou123** [comment]
> @F-loat 我是在最新的mpvue-entry quickStart模版里面使用，报下面的错误，你们都没碰到吗？
> 看了一下源码，是f2.js里面的报错
> 
> ![_20180911160259](https://user-images.githubusercontent.com/16076854/45346600-30be2380-b5dc-11e8-8fbd-a7dcec4edbae.png)

怎么解决
