### ISSUE TITLE
tooltip显示被截取&& 图例占据canvas高度导致绘图区域被压缩

### ISSUE THREAD

**Issue by qqqqq1y** [antvis/wx-f2#222]
- ![企业微信截图_15790812397369](https://user-images.githubusercontent.com/40757767/72422989-64a3ed00-37be-11ea-8d57-61e0efd364e6.png)

- ![企业微信截图_15790803093991](https://user-images.githubusercontent.com/40757767/72422923-463df180-37be-11ea-981d-6b93c2d9a8f8.png)

[文档例子](https://f2.antv.vision/zh/examples/line/basic#smooth)
import F2 from '@antv/f2';

const data = [{
  day: '周一',
  value: 300,
  line:'大家电'
}, {
  day: '周二',
  value: 400,
  line:'大家电'
}, {
  day: '周三',
  value: 350,
  line:'大家电'
}, {
  day: '周四',
  value: 500,
  line:'大家电'
}, {
  day: '周五',
  value: 490,
  line:'大家电'
}, {
  day: '周六',
  value: 600,
  line:'大家电'
}, {
  day: '周日',
  value: 900,
  line:'大家电'
},{
  day: '周一',
  value: 100,
  line:'小家电'
}, {
  day: '周二',
  value: 300,
  line:'小家电'
}, {
  day: '周三',
  value: 250,
  line:'小家电'
}, {
  day: '周四',
  value: 400,
  line:'小家电'
}, {
  day: '周五',
  value: 390,
  line:'小家电'
}, {
  day: '周六',
  value: 400,
  line:'小家电'
}, {
  day: '周日',
  value: 800,
  line:'小家电'
},{
  day: '周一',
  value: 245,
  line:'数码产品'
}, {
  day: '周二',
  value: 378,
  line:'数码产品'
}, {
  day: '周三',
  value: 358,
  line:'数码产品'
}, {
  day: '周四',
  value: 876,
  line:'数码产品'
}, {
  day: '周五',
  value: 698,
  line:'数码产品'
}, {
  day: '周六',
  value: 786,
  line:'数码产品'
}, {
  day: '周日',
  value: 789,
  line:'数码产品'
},{
  day: '周一',
  value: 423,
  line:'生活用品'
}, {
  day: '周二',
  value: 238,
  line:'生活用品'
}, {
  day: '周三',
  value: 258,
  line:'生活用品'
}, {
  day: '周四',
  value: 196,
  line:'生活用品'
}, {
  day: '周五',
  value: 489,
  line:'生活用品'
}, {
  day: '周六',
  value: 756,
  line:'生活用品'
}, {
  day: '周日',
  value: 956,
  line:'生活用品'
},{
  day: '周一',
  value: 356,
  line:'厨房用品'
}, {
  day: '周二',
  value: 644,
  line:'厨房用品'
}, {
  day: '周三',
  value: 675,
  line:'厨房用品'
}, {
  day: '周四',
  value: 354,
  line:'厨房用品'
}, {
  day: '周五',
  value: 874,
  line:'厨房用品'
}, {
  day: '周六',
  value: 965,
  line:'厨房用品'
}, {
  day: '周日',
  value: 987,
  line:'厨房用品'
},{
  day: '周一',
  value: 16323,
  line:'酒水饮料'
}, {
  day: '周二',
  value: 13665,
  line:'酒水饮料'
}, {
  day: '周三',
  value: 13485,
  line:'酒水饮料'
}, {
  day: '周四',
  value: 25359,
  line:'酒水饮料'
}, {
  day: '周五',
  value: 27218,
  line:'酒水饮料'
}, {
  day: '周六',
  value: 33586,
  line:'酒水饮料'
}, {
  day: '周日',
  value: 43556,
  line:'酒水饮料'
},{
  day: '周一',
  value: 26348,
  line:'五金制品'
}, {
  day: '周二',
  value: 35316,
  line:'五金制品'
}, {
  day: '周三',
  value: 38649,
  line:'五金制品'
}, {
  day: '周四',
  value: 46721,
  line:'五金制品'
}, {
  day: '周五',
  value: 43576,
  line:'五金制品'
}, {
  day: '周六',
  value: 56736,
  line:'五金制品'
}, {
  day: '周日',
  value: 63412,
  line:'五金制品'
},{
  day: '周一',
  value: 16578,
  line:'礼品鲜花'
}, {
  day: '周二',
  value: 25756,
  line:'礼品鲜花'
}, {
  day: '周三',
  value: 28547,
  line:'礼品鲜花'
}, {
  day: '周四',
  value: 32211,
  line:'礼品鲜花'
}, {
  day: '周五',
  value: 33546,
  line:'礼品鲜花'
}, {
  day: '周六',
  value: 43546,
  line:'礼品鲜花'
}, {
  day: '周日',
  value: 55712,
  line:'礼品鲜花'
},{
  day: '周一',
  value: 14678,
  line:'医药保健'
}, {
  day: '周二',
  value: 23546,
  line:'医药保健'
}, {
  day: '周三',
  value: 25749,
  line:'医药保健'
}, {
  day: '周四',
  value: 25781,
  line:'医药保健'
}, {
  day: '周五',
  value: 29246,
  line:'医药保健'
}, {
  day: '周六',
  value: 32396,
  line:'医药保健'
}, {
  day: '周日',
  value: 43172,
  line:'医药保健'
},{
  day: '周一',
  value: 14548,
  line:'汽车用品'
}, {
  day: '周二',
  value: 23436,
  line:'汽车用品'
}, {
  day: '周三',
  value: 24319,
  line:'汽车用品'
}, {
  day: '周四',
  value: 23481,
  line:'汽车用品'
}, {
  day: '周五',
  value: 29686,
  line:'汽车用品'
}, {
  day: '周六',
  value: 34596,
  line:'汽车用品'
}, {
  day: '周日',
  value: 48472,
  line:'汽车用品'
},{
  day: '周一',
  value: 1748,
  line:'个护清洁'
}, {
  day: '周二',
  value: 2326,
  line:'个护清洁'
}, {
  day: '周三',
  value: 2449,
  line:'个护清洁'
}, {
  day: '周四',
  value: 2681,
  line:'个护清洁'
}, {
  day: '周五',
  value: 2796,
  line:'个护清洁'
}, {
  day: '周六',
  value: 3796,
  line:'个护清洁'
}, {
  day: '周日',
  value: 4752,
  line:'个护清洁'
}];

const chart = new F2.Chart({
  id: 'container',
  pixelRatio: window.devicePixelRatio,
  height:220
});

const defs = {
  day: {
    range: [ 0, 1 ]
  },
  value: {
    tickCount: 5,
    min: 0,
  }
};
chart.source(data, defs);
chart.tooltip({
  showTitle:true,
  showCrosshairs: true
});
chart.line().position('day*value').shape('smooth').color('line');

chart.render(); 

1.tooltip中每个item的label + value 过长且item数量超过一定量时，tooltip会被裁剪掉一部分
2.生成的canvas包括图例，坐标系两部分， 图例过多会挤压坐标系高度

**Comment by zengyue** [comment]
https://github.com/antvis/F2/issues/766 这里跟进
