### ISSUE TITLE
文档里的如何使用应该再精细一点

### ISSUE THREAD

**Issue by niunan** [antvis/wx-f2#223]
初学，按readme里的使用说明，弄了好久都才弄出来的。。。
1. 需要在命令行下切换到小程序根目录下运行npm init ，然后不停的回车回车回车，让他自动创建package.json文件
2. 然后才执行那个npm install @an*** 才行
3. 然后按说明里的复制代码了，结果运行的时候是不报错了。但是不显示， 最后才发现是那个class="container"样式的问题。。把这个样式去掉了就显示图表了。我是新建一个小程序项目弄的

**Comment by zengyue** [comment]
已补充
