### ISSUE TITLE
构建的时候，找不到babel?

### ISSUE THREAD

**Issue by yaoboGit** [antvis/wx-f2#227]
![微信截图_20200127155005](https://user-images.githubusercontent.com/31029938/73157709-d49a6780-411c-11ea-8521-994e6c25eca8.png)

**Comment by yaoboGit** [comment]
1 D:\test\wx-f2-test\node_modules\@babel\runtime\index.js: 未找到npm包入口文件

**Comment by archtsv** [comment]
同问

**Comment by bynum** [comment]
也是同样的问题

**Comment by zengyue** [comment]
贴下复现步骤

**Comment by yaoboGit** [comment]
@zengyue 我按照官网的步骤执行，目前版本是2.0.1，就是在构建npm包的时候会弹出这个问题

**Comment by qqjt** [comment]
同有这个提示，另外按照 README 上的说明操作后，图表显示不出来，但页面上有内容。
windows 版开发者工具 1.02.1911180，基础库 2.10.1，"@antv/wx-f2": "^2.0.1"。

![捕获](https://user-images.githubusercontent.com/6744597/74014332-603bb000-49c9-11ea-88f0-779d06a684ed.PNG)
![2](https://user-images.githubusercontent.com/6744597/74014339-66319100-49c9-11ea-9a67-5146058d393b.PNG)

**Comment by mrzhangs520** [comment]
同问，按照步骤来，报以上错误，查了好多，貌似是新版本 babel 的问题，暂没有解决

**Comment by Emo1995** [comment]
同问

**Comment by xpauline24** [comment]
同问

**Comment by Yin-Xie** [comment]
同问

**Comment by Yin-Xie** [comment]
什么时候帮忙解决呀  好急啊 一直都是用这个库

**Comment by zengyue** [comment]
忽略吧，这个不影响的，本质上是因为微信的npm构建是自己独立的规则
