### ISSUE TITLE
小程序中 chart.pieLabel is not a function

### ISSUE THREAD

**Issue by ybrelax** [antvis/wx-f2#228]
![image](https://user-images.githubusercontent.com/31029938/74082989-0fe05300-4a9a-11ea-8049-af6edc49606a.png)

json:
```js
{
  "component": true,
  "usingComponents": {
    "f2": "@antv/wx-f2"
  }
}
```
请问还需要单独引入吗？我看到f2/lib/plugin/pie-label.js 有这个js；但是调用就报错了

**Comment by CarisL** [comment]
需要引入f2-all.min 具体可以看https://github.com/antvis/wx-f2/issues/144

**Comment by yaoboGit** [comment]
> 需要引入f2-all.min 具体可以看#144

我用的是npm引入的，这个你是说还要单独下载这个文件去引入吗？

**Comment by CarisL** [comment]
官方说用可以升级一下依赖
![image](https://user-images.githubusercontent.com/13416424/74085301-c4866e80-4ab2-11ea-9b7e-9dfaedd577bb.png)

**Comment by yaoboGit** [comment]
> 官方说用可以升级一下依赖
> ![image](https://user-images.githubusercontent.com/13416424/74085301-c4866e80-4ab2-11ea-9b7e-9dfaedd577bb.png)

我是直接下了官方封装的包
```js
"dependencies": {
    "@antv/wx-f2": "^2.0.1"
  }
```
我看了它里面这个依赖和 他说的一样
```js
"dependencies": {
    "@antv/f2": "~3.5.0"
  },
  "deprecated": false,
  "description": "F2 for weixin mini-program",
  "devDependencies": {
    "@rollup/plugin-commonjs": "^11.0.1",
    "@rollup/plugin-node-resolve": "^6.1.0",
    "eslint": "^6.8.0",
    "eslint-config-egg": "^8.0.0",
    "fs-extra": "^8.1.0",
    "pre-commit": "^1.2.2",
    "rollup": "^1.28.0"
  },
```
![image](https://user-images.githubusercontent.com/31029938/74085553-e680f080-4ab4-11ea-95e8-f4571fde8605.png)



请问下，能给我个小demo看下吗？我想知道自己是不是哪里搞错了

**Comment by CarisL** [comment]
我也是没有用pieLabel 用成功过lol

**Comment by yaoboGit** [comment]
😂😂

**Comment by TSjianjiao** [comment]
> 
> 
> 😂😂
这个版本看样子是不支持任何手势的，包括`interaction`也不能用

**Comment by CarisL** [comment]
> > 😂😂
> > 这个版本看样子是不支持任何手势的，包括`interaction`也不能用，楼上给的解决方法是针对老版本的

我找了老版本的也是不行。。。。。

**Comment by TSjianjiao** [comment]
> 
> 
> > > 😂😂
> > > 这个版本看样子是不支持任何手势的，包括`interaction`也不能用，楼上给的解决方法是针对老版本的
> 
> 我找了老版本的也是不行。。。。。

只有自己在`miniprogram_npm\@antv\wx-f2\index.js`里面仿照其他插件如`tooltip`，去注册一个，亲测可行

**Comment by CarisL** [comment]
可以加一个微信吗？之后有问题可以互相探讨。。。。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xu Hang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 上午10:51
收件人:&nbsp;"antvis/wx-f2"<wx-f2@noreply.github.com&gt;;
抄送:&nbsp;"罗漪"<845201776@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/wx-f2] 小程序中 chart.pieLabel is not a function (#228)



   
😂😂
 这个版本看样子是不支持任何手势的，包括interaction也不能用，楼上给的解决方法是针对老版本的
   
我找了老版本的也是不行。。。。。
  
只有自己在miniprogram_npm\@antv\wx-f2\index.js里面仿照其他插件如tooltip，去注册一个，亲测可行

**Comment by ybrelax** [comment]
> 可以加一个微信吗？之后有问题可以互相探讨。。。。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"xu Hang"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月6日(星期五) 上午10:51 收件人:&nbsp;"antvis/wx-f2"<wx-f2@noreply.github.com&gt;; 抄送:&nbsp;"罗漪"<845201776@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [antvis/wx-f2] 小程序中 chart.pieLabel is not a function (#228) 😂😂 这个版本看样子是不支持任何手势的，包括interaction也不能用，楼上给的解决方法是针对老版本的 我找了老版本的也是不行。。。。。 只有自己在miniprogram_npm\@AntV\wx-f2\index.js里面仿照其他插件如tooltip，去注册一个，亲测可行 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

可以，我用了老版的，目前还是能正常使用
![image](https://user-images.githubusercontent.com/31029938/76674092-a4345d00-65e6-11ea-9df7-a71655e62a08.png)

问题先这样吧

**Comment by zbx12** [comment]
在miniprogram_npm\@antv\wx-f2\index.js里面仿照其他插件如tooltip在这里怎么仿照，能给个参考吗@

**Comment by zbx12** [comment]
> > 可以加一个微信吗？之后有问题可以互相探讨。。。。
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "xu Hang"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年3月6日(星期五) 上午10:51 收件人: "antvis/wx-f2"<[wx-f2@noreply.github.com](mailto:wx-f2@noreply.github.com)>; 抄送: "罗漪"<[845201776@qq.com](mailto:845201776@qq.com)>;"Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [antvis/wx-f2] 小程序中 chart.pieLabel is not a function (#228) 😂😂 这个版本看样子是不支持任何手势的，包括interaction也不能用，楼上给的解决方法是针对老版本的 我找了老版本的也是不行。。。。。 只有自己在miniprogram_npm@AntV\wx-f2\index.js里面仿照其他插件如tooltip，去注册一个，亲测可行 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 可以，我用了老版的，目前还是能正常使用
> ![image](https://user-images.githubusercontent.com/31029938/76674092-a4345d00-65e6-11ea-9df7-a71655e62a08.png)
> 
> 问题先这样吧

能具体说明下这个问题是怎么仿照Tooltip的吗，还不是很明白

**Comment by sxy117** [comment]
有解决方案了吗  可以参考下不

**Comment by zwzy** [comment]
> 😂😂

在nodemodules中修改wx-f2 src 下的index.js 文件，将pielable 注册下，再打开@wx-f2重装安装些插件依赖，最后打包，小程序这边npm重新构建运行即可

**Comment by cv02040623** [comment]
我的也是报错，能提供一个小demo吗
