### ISSUE TITLE
构建报错未找到@babel\runtime\index.js npm包入口 急！急！急！

### ISSUE THREAD

**Issue by Yin-Xie** [antvis/wx-f2#230]
![image](https://user-images.githubusercontent.com/24772971/74621759-11d0a300-5179-11ea-83af-0fa94681927b.png)

**Comment by TSjianjiao** [comment]
因为依赖里面的`babel`的`package.json`里没有`main`字段，没有入口文件所以构建失败。我也不知道怎么解决，大概是要自己写个入口文件吧。

**Comment by Yin-Xie** [comment]
> 因为依赖里面的`babel`的`package.json`里没有`main`字段，没有入口文件所以构建失败。
> 我瞎搞了一下暂时没发现问题
> 
> 1. 下载安装这个包
> 2. 不要构建`npm`，先把`node_module`文件夹里面的`@babel`文件夹删除
> 3. 然后再构建`npm`
> 4. 这个仓库的例子有点问题，套`f2`组件的`view`需要指定高度，不然显示不出。其他的代码就按照仓库的例子就行了
> 
> ```
> <view style="height: 300px; width: 100%">
>   <f2 onInit="{{onInitChart}}" />
> </view>
> ```

谢谢你！我试了没报错了

**Comment by zengyue** [comment]
这个报错忽略掉就好了
