### ISSUE TITLE
页面滚动时，图表没有一起滚动，而是固定在原来位置

### ISSUE THREAD

**Issue by t1rry** [antvis/wx-f2#232]
* **F2 Version**:2.0.1
* **Platform**: 微信开发工具Stable v1.02.1911180
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

图表是写在一个长列表中的，在页面滚动的时候，图表没有跟着列表一起滚动，而是固定在原来位置（类似position:fixed效果），没有使用scrollview，有时在开发工具中选择iphoneX以上的机型没有这个问题。请问这个应该怎么处理？

**Comment by WangJiangJiaoZi** [comment]
canvas是原生组件， 微信开发者工具不支持调试。 手机上应该正常显示

**Comment by lingoworks** [comment]
一样遇到这个问题哦，有大佬解决了吗？

**Comment by t1rry** [comment]
> canvas是原生组件， 微信开发者工具不支持调试。 手机上应该正常显示

的确，在真机上这个问题就没有了

**Comment by liaokaime** [comment]
我就奇怪了，这么大个问题，为什么仍然没有解决
