### ISSUE TITLE
_this36.data.onInit is not a function;at SelectorQuery callback function引入报错

### ISSUE THREAD

**Issue by mam3** [antvis/wx-f2#236]
![image](https://user-images.githubusercontent.com/18628122/75087795-a3785000-557f-11ea-81ea-293f48c6e74e.png)

**Comment by mam3** [comment]
用的npm构建

**Comment by mam3** [comment]
1

**Comment by yuanye199169** [comment]
我也出现了相同问题，真机必报错，开发者工具时好时坏

**Comment by qmc2017** [comment]
![image](https://user-images.githubusercontent.com/32610758/78312355-149b2200-7586-11ea-9b1a-2f8fbf57c45d.png)
也报了这个错，宽高已设置
