### ISSUE TITLE
图例、tooltip、坐标轴显示乱码

### ISSUE THREAD

**Issue by bedisdover** [antvis/wx-f2#237]
按照 readme 中的指引操作后，图例、tooltip、坐标轴显示乱码，请问是什么问题呢？
* **F2 Version**: 3.5.0
* **Platform**: 安卓
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/11707559/75106899-68e3e580-565b-11ea-9e70-c5a1e324c77c.png)

* **CodePen Link**:

**Comment by zengyue** [comment]
看看是否是系统字体的问题？

**Comment by bedisdover** [comment]
> 看看是否是系统字体的问题？

你好，所有安卓机型都有这个问题，iOS 和开发工具里都是正常的

**Comment by bedisdover** [comment]
测试发现，应该是和多字体有关，按这个[issue](https://github.com/antvis/wx-f2/issues/260#issuecomment-603214114)设置了后就可以修复了
