### ISSUE TITLE
安卓手机折线图纵坐标不显示

### ISSUE THREAD

**Issue by oujinlong** [antvis/wx-f2#239]
小程序模拟器和iOS真机都没有问题

但是在安卓的真机上就不现实纵坐标

请问这个可能的原因是什么呢

**Comment by zengyue** [comment]
只有坐标轴不显示？

**Comment by jsuper1980** [comment]
遇到类似的问题，但更诡异。
1、模拟器显示有60px左右的位移，但在安卓和苹果真机上显示位置正常。
2、坐标轴和图例在iphone6和mi9上显示正常，但在P30p上不显示。

**Comment by oujinlong** [comment]
找到问题了,是微信小程序的 cavans bug, fillText() 在 cavans 2D 上不能显示数字和符号,你切换成中文就可以显示.
解决方案: 使用旧版的 F2 chart, 支持旧版的 cavans 就可以

**Comment by ybrelax** [comment]
> 找到问题了,是微信小程序的 cavans bug, fillText() 在 cavans 2D 上不能显示数字和符号,你切换成中文就可以显示.
> 解决方案: 使用旧版的 F2 chart, 支持旧版的 cavans 就可以

也就是目前这种npm方式不能显示数字？

**Comment by oujinlong** [comment]
是的,目前 npm 最新版本是 cavans 2D 的,所以不支持显示,可以去下载他老的版本,就用git 上那个扫码演示看到的版本
