### ISSUE TITLE
设置字体大小、粗细无效

### ISSUE THREAD

**Issue by TSjianjiao** [antvis/wx-f2#242]
* **F2 Version**:2.0.1
* **Platform**:全部
* **开发工具版本**: 1.02.1911180  目前最新版本
* **版本库**:也是最新
* **真机**:最新版的微信7.0.11，版本库也是最新1.10.2

```javascript
    chart.guide().text({
        position: ['50%', '60%'],
        content: 'xxxx',
        style: {
            fontSize: 25, 
        }
    });
```
这样设置之后，在开发工具里面能正常改变大小，而在真机上面，无论字体大小设多少都没有改变。基本上字体样式再真机上都不能实现
- 原因找到了，好像是新的`canvas`接口只提供了`context.font`设置字体，而且对于除了`sans-serif`的其他字体都有点问题？临时解决方法如下
- 找到[解决方法](https://gist.github.com/895be9266b487729629caed17519bce0.git)了，希望能在文档中提示下

**Comment by loknum** [comment]
你这个地址不翻墙 看不到阿

**Comment by zengyue** [comment]
chart.guide().text({
        position: ['50%', '60%'],
        content: 'xxx',
        style: {
            fill: '#01a2ea', 
            fontSize: 25, 
            fontWeight: 'bold',
            fontFamily: "sans-serif"
        }
    });

**Comment by fjc0k** [comment]
解决办法：

```js
F2.Global.setTheme({
  fontFamily: 'sans-serif',
})
```
