### ISSUE TITLE
4个问题，希望有人能回答一下

### ISSUE THREAD

**Issue by Super-Bin** [antvis/wx-f2#246]
## 没有提供完整的使用demo吗? 下图没有开源吗？
![WX20200307-151027](https://user-images.githubusercontent.com/26457469/76138848-d80f0000-6085-11ea-9eeb-385e4419d1ba.png)

## wx-f2和f2-canvas有什么区别？
wx-f2中引用了import F2 from '@antv/f2'; 
f2-canvas又使用了import F2 from '@antv/wx-f2'
两个都是组件，所以f2-canvas是可以直接在项目中使用的？

## 现在的f2-canvas项目结构中找不到lib目录了，是怎么回事，也没看到文档说明？
在网上找到以前的目录结构，现在不需要这些了？
├── f2-canvas                    // f2-canvas 组件        
│   ├── f2-canvas.js
│   ├── f2-canvas.json
│   ├── f2-canvas.wxml
│   ├── f2-canvas.wxss
│   └── lib                      // f2-canvas 组件依赖的类库
│       ├── EventEmitter.min.js  // 事件发射器，用于监听、触发事件， 3.1K
│       ├── f2.js                // f2 脚本（压缩），155K
│       └── renderer.js          // f2 专为适配微信小程序绘图上下文 context 而封装的伪 Canvas
├── pages                        // f2-canvas 组件使用示例

## 有交流群吗？

**Comment by zengyue** [comment]
直接用wx-f2 就可以了， f2-canvas 是1.x版本
