### ISSUE TITLE
为什么npm包这么大，都占用1.5M了。还有按照文档集成框架，直接报错HTMLCanvasView is not defined

### ISSUE THREAD

**Issue by juzihai** [antvis/wx-f2#248]
<img width="1680" alt="WX20200311-090401@2x" src="https://user-images.githubusercontent.com/30816445/76372084-49e19500-6377-11ea-8291-88437b3d9a6f.png">

<img width="1680" alt="WX20200311-090520@2x" src="https://user-images.githubusercontent.com/30816445/76372162-785f7000-6377-11ea-9c62-e65664812fec.png">

另外问一下，为什么这个npm包这么大，，都占用1.5M了。。这还怎么写其他代码呢

**Comment by zengyue** [comment]
https://github.com/antvis/wx-f2/issues/253#issuecomment-601053315
