### ISSUE TITLE
请问f2交互怎么弄

### ISSUE THREAD

**Issue by secularworld** [antvis/wx-f2#25]
这里面好像没有看到交互事件，能开放交互功能吗，应该怎么弄？直接在官网下的f2-all.min没有处理createElement类的方法，微信小程序不支持报错

**Comment by simaQ** [comment]
F2 3.2.0 beta 版本新增的交互目前还没有做小程序的适配呢，基于的是 Hammer.js 手势库，默认环境是 H5, 所以不支持微信小程序环境。

这一块我想想办法。

**Comment by secularworld** [comment]
嗯嗯，好的，麻烦了

**Comment by CarisL** [comment]
这一块现在有方案了吗

**Comment by CarisL** [comment]
f2-all.min 这个文件有更新吗？我应该下哪个版本 下载 3.3.1 版本的 会报 createElement of undefined
![image](https://user-images.githubusercontent.com/13416424/74019234-4783c800-49d2-11ea-91b3-c2c44de64ce2.png)
