### ISSUE TITLE
data-set 可以在小程序中支持吗？

### ISSUE THREAD

**Issue by ybrelax** [antvis/wx-f2#251]
![image](https://user-images.githubusercontent.com/31029938/76684450-1fc5f680-6647-11ea-8fe1-506eeec6e170.png)

关系图中的data-set 能在小程序中实现吗?

**Comment by zengyue** [comment]
可以的

**Comment by yinzhuoya** [comment]
> 可以的

请问怎么引入呢，可以给一个demo么？
