### ISSUE TITLE
出现闪退现象

### ISSUE THREAD

**Issue by ybrelax** [antvis/wx-f2#253]
微信版本： version 7.0.12

**Comment by ybrelax** [comment]
机型： 小米6

**Comment by pdap** [comment]
+1 小米10

**Comment by zengyue** [comment]
详细表述下， 并给个复现的demo

**Comment by ybrelax** [comment]
https://github.com/zengyue/f2-wx-demo
昨天拿您这个试了下，也不行，微信版本在 version 7.0.12， 其他版本可以

**Comment by ybrelax** [comment]
> 详细表述下， 并给个复现的demo

https://github.com/zengyue/f2-wx-demo
昨天拿您这个试了下，也不行，微信版本在 version 7.0.12， 其他版本可以

**Comment by Since-Dva** [comment]
小程序开发工具能看到，手机上预览就闪退，真机测试报错Uncaught (in promise) thirdScriptError
HTMLCanvasView is not defined
ReferenceError: HTMLCanvasView is not defined

**Comment by Lance-Ma** [comment]
微信版本在 version 7.0.12，小米6，9闪退

**Comment by zengyue** [comment]
https://developers.weixin.qq.com/community/develop/doc/000886c4e886e8f7c50a7b50859400 
https://developers.weixin.qq.com/community/develop/doc/0002220297cf70aacc19357a951c00

看起来是微信小程序的问题

**Comment by DreamPWJ** [comment]
@zengyue 不是官方bug,不是调试问题，是预览就不行 闪退 之前的wx-f2版本可以的啊，人家官方bug是调试不行，但是预览正常， 现在直接没发真机预览和体验了
