### ISSUE TITLE
r.Canvas is not a constructor

### ISSUE THREAD

**Issue by hank2718** [antvis/wx-f2#257]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/7368299/77224324-695e9600-6b9f-11ea-9ee4-b704110cdcd9.png)

**Comment by zengyue** [comment]
真机调试就会出现这个问题，微信本身框架的问题，官方demo也会有这个问题
