### ISSUE TITLE
用 wx-f2@2.x 版本试试，这个版本是使用了微信新的canvas方式

### ISSUE THREAD

**Issue by Jianing666** [antvis/wx-f2#265]
用 wx-f2@2.x 版本试试，这个版本是使用了微信新的canvas方式

_Originally posted by @zengyue in https://github.com/antvis/wx-f2/issues/238#issuecomment-592950960_
请问更新到2.1.0之后代码需要更改什么吗，我更新之后，控制台还是显示这个:
VM246:1 建议使用新 canvas 2d 接口提升渲染性能，详见文档：https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html#Canvas-2D-%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81

**Comment by zengyue** [comment]
根据readme使用就可以了
