### ISSUE TITLE
最新版本data.onInit is not a function;at SelectorQuery callback function

### ISSUE THREAD

**Issue by qmc2017** [antvis/wx-f2#266]
![f2](https://user-images.githubusercontent.com/32610758/78313349-013d8600-7589-11ea-9944-7c31d8f4b7bf.png)
宽高也设置了，找不到原因

**Comment by qmc2017** [comment]
还没有开始用，先测了一下demo，报了这个

**Comment by henan715** [comment]
在data中，初始化一个空函数：

**Comment by qmc2017** [comment]
> 在data中，初始化一个空函数：
> 
> ```js
> 数据： {
>     init ：（）=> {}
> }
> ```
> 
> 然后在wxml里面引用这个空函数

这个已经做了，还是会这样

**Comment by qmc2017** [comment]
又测了许多遍，还是报这个，和示例所做的并无任何差别，最近有人能成功吗

**Comment by qmc2017** [comment]
后来我成功了，我发现我把onInit没有写在data里，而是当作方法写在了下面，太难发现了。。。

**Comment by JuneYaooo** [comment]
求问怎么改啊，我也遇到了这个问题
