### ISSUE TITLE
wx-f2 和 f2-canvas该用哪一个

### ISSUE THREAD

**Issue by Dreamwht** [antvis/wx-f2#271]
我想请问一下，去年这个项目还有demo，现在demo该去哪里看？然后f2-canvas已经不再更新了嘛，里面依赖的wx-f2还是1.0的，我想升级怎么升级？再者这两个现在是要分开npm引入嘛，我操作了，没有成功。还望解惑，项目紧急

**Comment by zengyue** [comment]
demo 直接看 官网就可以了，https://f2.antv.vision/ ， wx-f2 2.0 是基于微信最新的canvas api，建议用wx-f2 2.0

**Comment by Dreamwht** [comment]
意思是微信小程序中直接引入wx-f2就好了，是嘛

**Comment by zengyue** [comment]
是的

**Comment by Dreamwht** [comment]
好的，谢谢，不过用法跟之前的感觉有些差异，网上资料也很少
