### ISSUE TITLE
最新的版本如何实现平移？调用API后没有任何效果，不知如何引入交互行为，多次尝试未果，求助！

### ISSUE THREAD

**Issue by qmc2017** [antvis/wx-f2#280]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by momolizi** [comment]
你好，我也出现这个问题，请问你解决了么？

**Comment by SimoralX** [comment]
同问

**Comment by zengyue** [comment]
https://github.com/antvis/wx-f2/issues/288
