### ISSUE TITLE
如何动态刷新数据重新渲染图表

### ISSUE THREAD

**Issue by hoshea1996** [antvis/wx-f2#290]
onInitChart(F2, config) {
      const chart = new F2.Chart(config);
      const data = [
        { value: 63.4, city: 'New York', date: '2011-10-01' },
        { value: 62.7, city: 'Alaska', date: '2011-10-01' },
        { value: 72.2, city: 'Austin', date: '2011-10-01' },
        { value: 58, city: 'New York', date: '2011-10-02' },
        { value: 59.9, city: 'Alaska', date: '2011-10-02' },
        { value: 67.7, city: 'Austin', date: '2011-10-02' },
        { value: 53.3, city: 'New York', date: '2011-10-03' },
        { value: 59.1, city: 'Alaska', date: '2011-10-03' },
        { value: 69.4, city: 'Austin', date: '2011-10-03' },
      ];
      chart.source(data, {
        date: {
          range: [0, 1],
          type: 'timeCat',
          mask: 'MM-DD'
        },
        value: {
          max: 300,
          tickCount: 4
        }
      });
      chart.area().position('date*value').color('city').adjust('stack');
      chart.line().position('date*value').color('city').adjust('stack');
      chart.render();
      // 注意：需要把chart return 出来
      return chart;
    }

wx-f2的master中的示例代码，在你重新插入数据源时，不知道在什么地方使用chart.changeData(data)方法来重新渲染图表。有没有人帮忙解答一下，比较急切！！！

**Comment by huisnotacouncillor** [comment]
同问怎么重新渲染数据？

我目前用了一个笨办法， 数据变了就重新设置函数

**Comment by huisnotacouncillor** [comment]
@hoshea1996 初次渲染（传入函数）之后， 可以通过selectComponent定位到图标组件， 图标组件（初次渲染之后）上有一个chart属性， 拿到这个属性之后调用changeData方法即可

**Comment by hoshea1996** [comment]
按照这种方式，确实能获取到目标组件，但是在组件中的data中并没有找到chart属性，因为按照github上的demo，并没有chart属性setData到data中去。

**Comment by pearmini** [comment]
你直接把 onInitChart 函数中返回的 chart 对象赋给一个变量：chart，在需要更新数据的时候调用：chart.changeData(newData)。

**Comment by liwenqi-cn** [comment]
大佬你那解决了没？我遇到这个问题，不知道如何下手呀

**Comment by 1015355299** [comment]
真机上根本就没有这个changeData属性

**Comment by hoshea1996** [comment]
> 大佬你那解决了没？我遇到这个问题，不知道如何下手呀

**Comment by hoshea1996** [comment]
> 真机上根本就没有这个changeData属性

微信开发者工具的真机调试不支持canvas-2d，wx-f2就是用canvas-2d封装的，所以获取不到，可以使用预览

**Comment by hoshea1996** [comment]
> 你直接把 onInitChart 函数中返回的 chart 对象赋给一个变量：chart，在需要更新数据的时候调用：chart.changeData(newData)。

这样就没法保持状态，如果我要用wx-f2在一个页面引用多次，就没法保持多个正常渲染数据

**Comment by hoshea1996** [comment]
> 大佬你那解决了没？我遇到这个问题，不知道如何下手呀

在应用wx-f2时给一个id，
<f2 id="wxf2" class="f2-chart" onInit="{{onChart}}" />

然后在父页面通过onLoad(Page时)或者attached(Component时)获取chart对象，
let wxF2 =   this.selectComponent('#wxf2') ，
这样，wxF2就能获取到wx-f2组件封装的chart对象了。

**Comment by JiangHaiYang01** [comment]
> chart

能够给出一个简单示例嘛

**Comment by curryhh** [comment]
求同，怎么解决的？

**Comment by gongzhw** [comment]
累死了，不知道怎么在页面上，展示多个图表，谁搞过啊

**Comment by shiny** [comment]
可以在 onLoad 时 `this.wxF2 = this.selectComponent('#wxf2')`
然后事件触发后（比如 ontap 时） `this.wxF2.chart.changeData` 把新数据传进去，图表就发生变化了
