### ISSUE TITLE
我在微信小程序上用f2，当x轴的label达到12个，文字会重叠在一起

### ISSUE THREAD

**Issue by miliPolo** [antvis/wx-f2#293]
我这边设置x轴的数据格式是这样的：
chart.scale('x', {
      tickCount: 12,
      type: '', // 声明 type 字段为分类类型
      values: [ '周一上', '周一下', '周二上', '周二下', '周三上', '周三下', '周四上', '周四下', '周五上', '周五下', '周六上', '周六下' ], // 重新显示的值
      alias: '类型' // 设置属性的别名
    });
然后在手机上显示的文字都重叠了，想问下支持将文字按照45°斜着放置吗

**Comment by miliPolo** [comment]
附上截图
![image](https://user-images.githubusercontent.com/11912376/83720078-ec559f80-a66a-11ea-9558-d89a2f377490.png)

**Comment by zengyue** [comment]
https://f2.antv.vision/zh/examples/component/axis#rotate
