### ISSUE TITLE
wx-f2在2.x.x版本上，chart.scrollBar时出现了chart.scrollBar is not a function问题

### ISSUE THREAD

**Issue by hoshea1996** [antvis/wx-f2#295]
使用2.x.x版本的wx-f2时，使用chart.scrollBar时出现了
chart.scrollBar is not a function;at SelectorQuery callback function
TypeError: chart.scrollBar is not a function

想问这个问题如何解决？？？

**Comment by dai-siki** [comment]
我也碰到了这个问题，专门手改了一个scrollBar的plugin，结果发现卡在了

**Comment by hoshea1996** [comment]
> 我也碰到了这个问题，专门手改了一个scrollBar的plugin，结果发现卡在了
> `chart.interaction("pan");`
> 目前还不知道怎么改。
> 
> 手改scrollBar附录如下，有缘人自取。
> [调用方法](https://www.yuque.com/antv/f2/api-scroll-bar)
> 
> ```
> const Helper = {
>   getLimitRange(data, scale) {
>     function toTimeStamp(value) {
>       if (typeof value === "string") {
>         if (value.indexOf("T") > 0) {
>           value = new Date(value).getTime();
>         } else {
>           value = new Date(value.replace(/-/gi, "/")).getTime();
>         }
>       }
> 
>       if (value instanceof Date) {
>         value = value.getTime();
>       }
> 
>       return value;
>     }
>     function getRange(values) {
>       if (!values.length) {
>         return {
>           min: 0,
>           max: 0,
>         };
>       }
> 
>       var max = Math.max.apply(null, values);
>       var min = Math.min.apply(null, values);
>       return {
>         min: min,
>         max: max,
>       };
>     }
> 
>     var result;
>     var field = scale.field,
>       type = scale.type;
>     var values = data.map((item) => item[field]);
> 
>     if (type === "linear") {
>       result = getRange(values);
> 
>       if (scale.min < result.min) {
>         result.min = scale.min;
>       }
> 
>       if (scale.max > result.max) {
>         result.max = scale.max;
>       }
>     } else if (type === "timeCat") {
>       values.forEach((v, i) => {
>         values[i] = toTimeStamp(v);
>       });
>       values.sort(function (v1, v2) {
>         return v1 - v2;
>       });
>       result = values;
>     } else {
>       result = values;
>     }
> 
>     return result;
>   },
>   getFieldRange(scale, limitRange, type) {
>     if (!scale) return [0, 1];
>     var minRatio = 0;
>     var maxRatio = 0;
> 
>     if (type === "linear") {
>       var min = limitRange.min,
>         max = limitRange.max;
>       minRatio = (scale.min - min) / (max - min);
>       maxRatio = (scale.max - min) / (max - min);
>     } else {
>       var originValues = limitRange;
>       var values = scale.values || [];
>       var firstIndex = originValues.indexOf(values[0]);
>       var lastIndex = originValues.indexOf(values[values.length - 1]);
>       minRatio = firstIndex / (originValues.length - 1);
>       maxRatio = lastIndex / (originValues.length - 1);
>     }
> 
>     return [minRatio, maxRatio];
>   },
> };
> 
> const Util = {
>   isObject(value) {
>     var type = typeof value;
>     return (value !== null && type === "object") || type === "function";
>   },
>   deepMix(rst) {
>     function is_plain_object_1(value) {
>       if (typeof value !== "object") {
>         return false;
>       }
>       if (Object.getPrototypeOf(value) === null) {
>         return true;
>       }
>       var proto = value;
>       while (Object.getPrototypeOf(proto) !== null) {
>         proto = Object.getPrototypeOf(proto);
>       }
>       return Object.getPrototypeOf(value) === proto;
>     }
> 
>     var MAX_MIX_LEVEL = 5;
> 
>     function _deepMix(dist, src, level, maxLevel) {
>       level = level || 0;
>       maxLevel = maxLevel || MAX_MIX_LEVEL;
>       for (var key in src) {
>         if (src.hasOwnProperty(key)) {
>           var value = src[key];
>           if (value !== null && is_plain_object_1(value)) {
>             if (!is_plain_object_1(dist[key])) {
>               dist[key] = {};
>             }
>             if (level < maxLevel) {
>               _deepMix(dist[key], value, level + 1, maxLevel);
>             } else {
>               dist[key] = src[key];
>             }
>           } else if (Array.isArray(value)) {
>             dist[key] = [];
>             dist[key] = dist[key].concat(value);
>           } else if (value !== undefined) {
>             dist[key] = value;
>           }
>         }
>       }
>     }
> 
>     var args = [];
>     for (var _i = 1; _i < arguments.length; _i++) {
>       args[_i - 1] = arguments[_i];
>     }
>     for (var i = 0; i < args.length; i += 1) {
>       _deepMix(rst, args[i]);
>     }
>     return rst;
>   },
>   directionEnabled(mode, dir) {
>     if (mode === undefined) {
>       return true;
>     } else if (typeof mode === "string") {
>       return mode.indexOf(dir) !== -1;
>     }
> 
>     return false;
>   },
> };
> 
> const DEFAULT_CFG = {
>   mode: "x",
>   xStyle: {
>     backgroundColor: "rgba(202, 215, 239, .2)",
>     fillerColor: "rgba(202, 215, 239, .5)",
>     size: 4,
>     lineCap: "round",
>     offsetX: 0,
>     offsetY: 8,
>   },
>   yStyle: {
>     backgroundColor: "rgba(202, 215, 239, .2)",
>     fillerColor: "rgba(202, 215, 239, .5)",
>     size: 4,
>     lineCap: "round",
>     offsetX: 8,
>     offsetY: 0,
>   },
> };
> 
> export default {
>   init: function init(chart) {
>     chart.set("_limitRange", {});
> 
>     chart.scrollBar = function (cfg) {
>       if (cfg === true) {
>         cfg = DEFAULT_CFG;
>       } else if (Util.isObject(cfg)) {
>         cfg = Util.deepMix({}, DEFAULT_CFG, cfg);
>       }
> 
>       this.set("_scrollBarCfg", cfg);
>     };
>   },
>   clear: function clear(chart) {
>     chart.set("_limitRange", {});
>   },
>   changeData: function changeData(chart) {
>     chart.set("_limitRange", {});
>   },
>   clearInner: function clearInner(chart) {
>     var hBar = chart.get("_horizontalBar");
>     var vBar = chart.get("_verticalBar");
>     hBar && hBar.remove(true);
>     vBar && vBar.remove(true);
>     chart.set("_horizontalBar", null);
>     chart.set("_verticalBar", null);
>   },
>   afterGeomDraw: function afterGeomDraw(chart) {
>     var scrollBarCfg = chart.get("_scrollBarCfg");
>     if (!scrollBarCfg) return;
>     var data = chart.get("data");
>     var plotRange = chart.get("plotRange");
>     var backPlot = chart.get("backPlot");
>     var canvas = chart.get("canvas");
>     var canvasHeight = canvas.get("height");
>     var limitRange = chart.get("_limitRange");
>     var mode = scrollBarCfg.mode;
> 
>     if (Util.directionEnabled(mode, "x")) {
>       var _scrollBarCfg$xStyle = scrollBarCfg.xStyle,
>         offsetX = _scrollBarCfg$xStyle.offsetX,
>         offsetY = _scrollBarCfg$xStyle.offsetY,
>         lineCap = _scrollBarCfg$xStyle.lineCap,
>         backgroundColor = _scrollBarCfg$xStyle.backgroundColor,
>         fillerColor = _scrollBarCfg$xStyle.fillerColor,
>         size = _scrollBarCfg$xStyle.size;
>       var xScale = chart.getXScale();
>       var xLimitRange = limitRange[xScale.field];
> 
>       if (!xLimitRange) {
>         xLimitRange = Helper.getLimitRange(data, xScale);
>         limitRange[xScale.field] = xLimitRange;
>       }
> 
>       var currentRange = Helper.getFieldRange(xScale, xLimitRange, xScale.type);
>       var horizontalBar = chart.get("_horizontalBar");
>       var yPos = canvasHeight - size / 2 + offsetY;
> 
>       if (horizontalBar) {
>         var progressLine = horizontalBar.get("children")[1];
>         progressLine.attr({
>           x1: Math.max(
>             plotRange.bl.x + plotRange.width * currentRange[0] + offsetX,
>             plotRange.bl.x
>           ),
>           x2: Math.min(
>             plotRange.bl.x + plotRange.width * currentRange[1] + offsetX,
>             plotRange.br.x
>           ),
>         });
>       } else {
>         horizontalBar = backPlot.addGroup({
>           className: "horizontalBar",
>         });
>         horizontalBar.addShape("line", {
>           attrs: {
>             x1: plotRange.bl.x + offsetX,
>             y1: yPos,
>             x2: plotRange.br.x + offsetX,
>             y2: yPos,
>             lineWidth: size,
>             stroke: backgroundColor,
>             lineCap: lineCap,
>           },
>         });
>         horizontalBar.addShape("line", {
>           attrs: {
>             x1: Math.max(
>               plotRange.bl.x + plotRange.width * currentRange[0] + offsetX,
>               plotRange.bl.x
>             ),
>             y1: yPos,
>             x2: Math.min(
>               plotRange.bl.x + plotRange.width * currentRange[1] + offsetX,
>               plotRange.br.x
>             ),
>             y2: yPos,
>             lineWidth: size,
>             stroke: fillerColor,
>             lineCap: lineCap,
>           },
>         });
>         chart.set("_horizontalBar", horizontalBar);
>       }
>     }
> 
>     if (Util.directionEnabled(mode, "y")) {
>       var _scrollBarCfg$yStyle = scrollBarCfg.yStyle,
>         _offsetX = _scrollBarCfg$yStyle.offsetX,
>         _offsetY = _scrollBarCfg$yStyle.offsetY,
>         _lineCap = _scrollBarCfg$yStyle.lineCap,
>         _backgroundColor = _scrollBarCfg$yStyle.backgroundColor,
>         _fillerColor = _scrollBarCfg$yStyle.fillerColor,
>         _size = _scrollBarCfg$yStyle.size;
>       var yScale = chart.getYScales()[0];
>       var yLimitRange = limitRange[yScale.field];
> 
>       if (!yLimitRange) {
>         yLimitRange = Helper.getLimitRange(data, yScale);
>         limitRange[yScale.field] = yLimitRange;
>       }
> 
>       var _currentRange = Helper.getFieldRange(
>         yScale,
>         yLimitRange,
>         yScale.type
>       );
> 
>       var verticalBar = chart.get("_verticalBar");
>       var xPos = _size / 2 + _offsetX;
> 
>       if (verticalBar) {
>         var _progressLine = verticalBar.get("children")[1];
> 
>         _progressLine.attr({
>           y1: Math.max(
>             plotRange.tl.y + plotRange.height * _currentRange[0] + _offsetY,
>             plotRange.tl.y
>           ),
>           y2: Math.min(
>             plotRange.tl.y + plotRange.height * _currentRange[1] + _offsetY,
>             plotRange.bl.y
>           ),
>         });
>       } else {
>         verticalBar = backPlot.addGroup({
>           className: "verticalBar",
>         });
>         verticalBar.addShape("line", {
>           attrs: {
>             x1: xPos,
>             y1: plotRange.tl.y + _offsetY,
>             x2: xPos,
>             y2: plotRange.bl.y + _offsetY,
>             lineWidth: _size,
>             stroke: _backgroundColor,
>             lineCap: _lineCap,
>           },
>         });
>         verticalBar.addShape("line", {
>           attrs: {
>             x1: xPos,
>             y1: Math.max(
>               plotRange.tl.y + plotRange.height * _currentRange[0] + _offsetY,
>               plotRange.tl.y
>             ),
>             x2: xPos,
>             y2: Math.min(
>               plotRange.tl.y + plotRange.height * _currentRange[1] + _offsetY,
>               plotRange.bl.y
>             ),
>             lineWidth: _size,
>             stroke: _fillerColor,
>             lineCap: _lineCap,
>           },
>         });
>         chart.set("_verticalBar", verticalBar);
>       }
>     }
>   },
> };
> ```

你有使用到不是默认交互的插件没，比如ScrollBar之类的需要另行引入chart对象中的，我这里出现国这种问题了。

**Comment by SimoralX** [comment]
参见我另一个回答：[https://github.com/antvis/wx-f2/issues/300#issuecomment-653774690](https://github.com/antvis/wx-f2/issues/300#issuecomment-653774690)

**Comment by hoshea1996** [comment]
thanks
