### ISSUE TITLE
wx-f2如何引入ScrollBar,默认添加的交互中没有ScrollBar

### ISSUE THREAD

**Issue by hoshea1996** [antvis/wx-f2#300]
在使用wx-f2时，使用
```

chart.scrollBar({
  // 一些配置项
  mode: 'y',
  yStyle: {
    xStyle: {
      offsetY: -5
    }
  }
});
```
出现了` scroll-bar.js" is not defined`以下错误
![scrollBar](https://user-images.githubusercontent.com/63483373/85353171-35966200-b53a-11ea-8c80-530041e1f19f.png)

有没有同样使用2.x.x版本的wx-f2遇到并解决该坑的小伙伴呀，比较急呀

**Comment by SimoralX** [comment]
```js
const ScrollBar = require('@antv/f2/lib/plugin/scroll-bar');  // 这个路径是node_module的，你需要修改为miniprogram_npm的

self.dayChart = (F2, config) => {
          const chart = new F2.Chart({ ...config, plugins: ScrollBar });
          // ......
});
```

**Comment by SimoralX** [comment]
> ```js
> const ScrollBar = require('@antv/f2/lib/plugin/scroll-bar');  // 这个路径是node_module的，你需要修改为miniprogram_npm的
> 
> self.dayChart = (F2, config) => {
>           const chart = new F2.Chart({ ...config, plugins: ScrollBar });
>           // ......
> });
> ```
> 
> 但是捏，我那个平移交互还没研究明白，等我明白了再来更

平移交互 pan 的已经研究明白了，这是链接：https://github.com/antvis/wx-f2/issues/305#issuecomment-658594610

**Comment by curryhh** [comment]
@SimoralX 大佬是怎么解决的？我也遇到了

**Comment by hoshea1996** [comment]
thanks
