### ISSUE TITLE
2.0 新版本怎么引用 interaction？

### ISSUE THREAD

**Issue by SimoralX** [antvis/wx-f2#305]
直接使用 `chart.interaction('pan');` 没效果啊！

再次注册这个

```
F2.Chart.registerInteraction('pan1', Pan);
```

结果X轴以及标注可以平移了，但是柱状图里的柱没平移啊

**Comment by SimoralX** [comment]
解决了，解决方式有点绕，有更好的办法请告诉我，下面是代码：


```js
// 第一步：加载pan这个交互行为
const Pan = require('@antv/f2/lib/interaction/pan');

onInitChart(F2, config) {
  // 第二步：注册交互行为Pan
  F2.Chart.registerInteraction('wxPan', Pan);
  
  const chart = new F2.Chart(config);  
  
  // ...... 省略一些无关代码

  chart.interaction('wxPan'); // 使用pan这个交互行为
  
  chart.render();
  // 注意：需要把chart return 出来
  return chart;
}
```

**Comment by singlelove** [comment]
@SimoralX const Pan = require('@antv/f2/lib/interaction/pan');按照这个路径加载提示not defined找不到包。已经安装f2，并且执行了npm构建，我看miniprogram_npm目录下的@antv/f2只有index.js跟index.js.map没有lib目录

**Comment by SimoralX** [comment]
> @SimoralX const Pan = require('@antv/f2/lib/interaction/pan');按照这个路径加载提示not defined找不到包。已经安装f2，并且执行了npm构建，我看miniprogram_npm目录下的@antv/f2只有index.js跟index.js.map没有lib目录

@singlelove 我使用的是mpx这个框架，如果你是使用微信小程序原生语法，那么就需要修改引用路径为 miniprogram_npm 下的路径。

**Comment by kingslary** [comment]
const Pan = require('@antv/f2/lib/interaction/pan');按照这个路径加载提示not defined找不到包。已经安装f2，并且执行了npm构建，我看miniprogram_npm目录下的@antv/f2只有index.js跟index.js.map没有lib目录

**Comment by SimoralX** [comment]
> const Pan = require('@antv/f2/lib/interaction/pan');按照这个路径加载提示not defined找不到包。已经安装f2，并且执行了npm构建，我看miniprogram_npm目录下的@antv/f2只有index.js跟index.js.map没有lib目录

安装这个依赖："@antv/wx-f2": "^2.1.0",
安装方法：npm install @antv/wx-f2 --save

**Comment by Backlight87** [comment]
同问const Pan = require('@antv/f2/lib/interaction/pan');
找不到，在node_modules里面是有的但是就是引用不到
![image](https://user-images.githubusercontent.com/25681077/108980574-c5427080-76c6-11eb-8626-6eddbba97275.png)
