### ISSUE TITLE
求助，使用wx-f2,ios端微信出现闪退

### ISSUE THREAD

**Issue by tcyufeng** [antvis/wx-f2#307]
@antv/wx-f2版本 ： 2.1.0
微信版本 ： ios，7.0.14
代码片段：https://developers.weixin.qq.com/s/J52wdHmM7ziO
点击首页按钮，然后返回，再进入，再返回，重复操作，使图表反复渲染，基本10次以内必现

**Comment by WowLv** [comment]
同问，ios13 微信7.0.14 图表渲染几次后会闪退

**Comment by WowLv** [comment]
用到tooltip的时候，真机预览就会出现

**Comment by WowLv** [comment]
是个bug吗？还是使用的时候哪里需要注意

**Comment by SimoralX** [comment]
同问，ios闪退，在重新绘制之前先 clear , 一样会闪退

**Comment by tcyufeng** [comment]
https://developers.weixin.qq.com/community/develop/doc/0006e208cc0800bee09a5083256c00
是微信的bug
![image](https://user-images.githubusercontent.com/28287106/88516398-ccfe4180-d01f-11ea-8102-988b662fe733.png)
