### ISSUE TITLE
微信小程序demo源码到底在哪啊

### ISSUE THREAD

**Issue by tcyufeng** [antvis/wx-f2#308]
![image](https://user-images.githubusercontent.com/28287106/87002450-355dbe00-c1ec-11ea-9eb4-bedf85f828aa.png)
这个源码到底在哪啊，翻了好几遍没找到

**Comment by SimoralX** [comment]
切换到 **imgbot** 分支

注意：这个是基于1.x版本，不是现在2.x的版本

**Comment by tcyufeng** [comment]
> 切换到 **imgbot** 分支
> 
> 注意：这个是基于1.x版本，不是现在2.x的版本

好的谢谢
