### ISSUE TITLE
wx-f2出现重新渲染 pixelRatio失效的问题

### ISSUE THREAD

**Issue by kyleWong1011** [antvis/wx-f2#309]
首次渲染是正常的
![首次渲染](https://p.qlogo.cn/qqmail_head/oA62fHtPSY5lf4eYY0IVRhC3q7mC3MJXNJuKfeiciaPk0bRTc2jKSibbpTftgYdNHcB/0)

第二次渲染后比例就不对了
![重复渲染](https://p.qlogo.cn/qqmail_head/oA62fHtPSY5lf4eYY0IVRhC3q7mC3MJXc6Ns9AJMibEBTia5VYph7TVzSiaiaQtY9icMic/0)

控制台打印config选项参数的 width, height, pixelRatio 并没有变
![控制台log](https://p.qlogo.cn/qqmail_head/oA62fHtPSY5lf4eYY0IVRhC3q7mC3MJXNJuKfeiciaPk037xIiafjmMXWLl6K9Eoiclk/0)

**Comment by zengyue** [comment]
对啊，看起来没有问题啊

**Comment by Elliott-Hu** [comment]
同样的问题

**Comment by zengyue** [comment]
> 同样的问题

代码贴一下看看

**Comment by Elliott-Hu** [comment]
#275

**Comment by zengyue** [comment]
https://github.com/antvis/wx-f2/issues/309 这里统一跟进
