### ISSUE TITLE
f2数据更新问题

### ISSUE THREAD

**Issue by secularworld** [antvis/wx-f2#31]
看到之前提问里面有说到用chart.changeData(data) 但是报错了，请问该怎么用啊

**Comment by simaQ** [comment]
更新数据的话，直接调用 chart.changeData(data) 既可以了，用法很简单的。只是更新的数据源数据结构需要和原始数据相同。

demo: https://codepen.io/Sima/pen/NzeWwN

**Comment by secularworld** [comment]
嗯嗯，好的，找到问题了，chart这个变量设成局部的了，找不到所以报错，多谢

**Comment by cafehaus** [comment]
> 更新数据的话，直接调用 chart.changeData(data) 既可以了，用法很简单的。只是更新的数据源数据结构需要和原始数据相同。
> 
> demo: https://codepen.io/Sima/pen/NzeWwN

我直接用chart.changeData(data)更新数据，渲染会有问题，要把动画关了才行animate: false
