### ISSUE TITLE
插件为什么不绘制呢？

### ISSUE THREAD

**Issue by hhzhldhjl** [antvis/wx-f2#317]
使用：
 <f2 class="f2" data="{{data}}" bind:draw="draw" />
Page({
  data: {
    data:[
      { value: 123, type: '运行指数', date: '10/01' },
      { value: 62, type: '历史均值', date: '10/01' },
      { value: 212, type: '运行指数', date: '10/02' },
      { value: 59, type: '历史均值', date: '10/02' },
      { value: 53, type: '运行指数', date: '10/03' },
      { value: 210, type: '历史均值', date: '10/03' },
      { value: 162, type: '运行指数', date: '10/04' },
      { value: 1, type: '历史均值', date: '10/04' }
    ]
  },
  draw ({ detail: { chart, data } }) {
    chart.source(data, {
      date: {
        range: [0.05, 0.95]
      }
    })
    chart.legend('type', {
      align: 'right',
      itemWidth: 80
    })
    chart.line().shape('smooth').position('date*value').color('type', ['#de5341', '#4a81ed'])
    chart.area().shape('smooth').position('date*value')
      .color('type', ['l(90) 0:#de5341 1:#ffffff', 'l(90) 0:#4a81ed 1:#ffffff'])

    // 无需render
  }
});
也不报错，也不绘制，draw方法也不执行

**Comment by zengyue** [comment]
用2.x 吧，使用方式看readme
