### ISSUE TITLE
真机调试时提示"Cannot read property 'createView' of undefined"

### ISSUE THREAD

**Issue by codingZXY** [antvis/wx-f2#324]
图表在开发工具里可以正常加载显示，在真机调试时，提示 "Cannot read property 'createView' of undefined"。不知道是不是微信小程序的问题，因为用echarts-for-weixin的图表时，也出现了同样提示。

**Comment by codingZXY** [comment]
![Uploading image.png…]()

**Comment by codingZXY** [comment]
![1601276297(1)](https://user-images.githubusercontent.com/22216251/94400055-10e60200-019b-11eb-90c0-0201b7bdcc54.jpg)

**Comment by zengyue** [comment]
嗯，微信小程序不支持canvas真机调试

**Comment by codingZXY** [comment]
> 嗯，微信小程序不支持canvas真机调试

好的 刚刚用体验版试了一下没问题 感谢！
