### ISSUE TITLE
我按照咱们例子做出图表了，但是点击没有反应

### ISSUE THREAD

**Issue by 969723815** [antvis/wx-f2#34]
我按照咱们例子做出图表了，但是点击没有反应，是不是哪里需要配置
这是我的
![tim 20180704132725](https://user-images.githubusercontent.com/34827395/42258415-3b52102e-7f8e-11e8-8cab-f8ac36183a00.png)
这是我运行官方例子
![tim 20180704132801](https://user-images.githubusercontent.com/34827395/42258425-4c30172e-7f8e-11e8-83c5-9b4756820daf.png)

**Comment by cafehaus** [comment]
原因：未适配小程序的事件机制
解决方案：把这段代码放到import F2 from 'xxxx'下面

F2.Util.addEventListener = function (source, type, listener) {
  source.addListener(type, listener);
};
F2.Util.removeEventListener = function (source, type, listener) {
  source.removeListener(type, listener);
};
F2.Util.createEvent = function (event, chart) {
  const type = event.type;
  let x = 0;
  let y = 0;
  const touches = event.touches;
  if (touches && touches.length > 0) {
    x = touches[0].x;
    y = touches[0].y;
  }
  return {
    type,
    chart,
    x,
    y
  };
};

**Comment by zengyue** [comment]
用2.x版本
