### ISSUE TITLE
图例的文字颜色配置要怎么设置，看了文档没有呀？

### ISSUE THREAD

**Issue by yaotaiye** [antvis/wx-f2#36]
![7y shbldo dcb9 ro l](https://user-images.githubusercontent.com/24998871/42306126-62809166-8060-11e8-9267-42e822982133.png)
图例的文字颜色配置要怎么设置，看了文档没有呀？

**Comment by douhaoi** [comment]
> @simaQ 你好，我有三个小问题，我现在目前在小程序里面使用F2，1.我用了自定义图例，但是用你上面回答的那个方法不能实现对文字颜色的设置。2.Y轴能跟X轴一样画一条线吗？然后刻度还存在。 3.针对折线图的X轴刻度的虚线能能够删除吗？下面是我的截图
> 
> ![_20190120032715](https://user-images.githubusercontent.com/29974533/51431417-68606a80-1c63-11e9-9ce8-1dc7a7d7e7b3.png)

第二个问题跟第三个问题我已经解决了，还差第一个，谢谢

**Comment by douhaoi** [comment]
> > @simaQ 你好，我有三个小问题，我现在目前在小程序里面使用F2，1.我用了自定义图例，但是用你上面回答的那个方法不能实现对文字颜色的设置。2.Y轴能跟X轴一样画一条线吗？然后刻度还存在。 3.针对折线图的X轴刻度的虚线能能够删除吗？下面是我的截图
> > ![_20190120032715](https://user-images.githubusercontent.com/29974533/51431417-68606a80-1c63-11e9-9ce8-1dc7a7d7e7b3.png)
> 
> 第二个问题跟第三个问题我已经解决了，还差第一个，谢谢

这里是我设置图例的代码
![123](https://user-images.githubusercontent.com/29974533/51431740-2259d580-1c68-11e9-8c88-d720d61e6d3e.png)
