### ISSUE TITLE
手机上图表区无法滑动，我们有超出一屏的需求

### ISSUE THREAD

**Issue by yanhan569046480** [antvis/wx-f2#37]

**Comment by yanhan569046480** [comment]
@simaQ 嗯嗯，好的，加油，小姐姐![image](https://user-images.githubusercontent.com/1505382/42439610-fb808b68-8395-11e8-94f4-7a12f02f74f8.png)![image](https://user-images.githubusercontent.com/1505382/42439612-fbeb1230-8395-11e8-8300-10eb5121c69d.png)![image](https://user-images.githubusercontent.com/1505382/42439613-fc211646-8395-11e8-8ea4-024a786d00a9.png)

**Comment by pocketChao** [comment]
> 这个稍等下，我正在封装，将这个交互兼容小程序

小姐姐兼容了么

**Comment by simaQ** [comment]
@pocketChao 自己扫码看下提供的 demo，已经支持 pan 平移交互了。

**Comment by chenycu** [comment]
@simaQ 现在是可以平移交互，但是在canvas区域上下滑动会很卡顿。不停的滑动卡主，需要在其他区域滑下才能恢复。希望能解决下
