### ISSUE TITLE
安卓上，环形图，如果有值为0的项，那个颜色会填充整个内圆，请问有解决办法吗？

### ISSUE THREAD

**Issue by yanhan569046480** [antvis/wx-f2#40]
![image](https://user-images.githubusercontent.com/1505382/42443912-5c546a6c-83a1-11e8-8df0-f03afbc33be1.png)
@simaQ 如上图所示，手机为锤子科技坚果pro，系统版本Android 7.1.1

**Comment by yanhan569046480** [comment]
还有选择项提示信息的虚线也没有显示出来

**Comment by dxq613** [comment]
有值为0全部填充应该是bug，虚线绘制不出来估计没办法，说明机型的浏览器不支持虚线的方法

**Comment by 11120** [comment]
请问官方有解决吗？我也遇到这问题了，ios是ok的

**Comment by simaQ** [comment]
稍等，我跟进一下

**Comment by ire-solas** [comment]
`const pie_data = ringData;
  chartPie = new F2.Chart({
    el: canvas,
    width: width,
    height: height,
  });
chartPie.source(pie_data);
  chartPie.coord('polar', {
    transposed: true,
    innerRadius: 0.618,
    radius: 1
  });
  chartPie.axis(false);
  chartPie.legend('notReachingType', {
    position: 'left',
    verticalAlign: 'middle',
    itemFormatter: function itemFormatter(val) {
      return val + '  ' + map[val];
    }
  });

  chartPie.tooltip(false);
  chartPie.interval().position('month*ratio').color('notReachingType').adjust('stack');

  chartPie.render();
  return chartPie;`
当ration为零时，有些Android机会遇到圆心被填充的问题，iOS不会出现。

**Comment by simaQ** [comment]
@ire-solas 能提供数据吗？

![image](https://user-images.githubusercontent.com/6628666/44636107-5512e100-a9dc-11e8-8517-0efa32ee5936.png)

**Comment by ire-solas** [comment]
@simaQ 
`{month:"8月"
notReachingAmount:98560446.22
notReachingNum:1842
notReachingType:"银行已付企业未付"
ratio:0.518364785023358}`

**Comment by misszoessmile** [comment]
同样的问题+1

**Comment by Ycenx** [comment]
这个问题解决了吗

**Comment by Ycenx** [comment]
@yanhan569046480 这个问题解决了吗

**Comment by xingyuehaiqing** [comment]
我也出现了这个问题

**Comment by John-jin** [comment]
@simaQ  这个问题到现在处理好了吗

**Comment by yanhan569046480** [comment]
已离职，现在没搞小程序了，关了吧，拖延症有点严重，不好意思☺️

**Comment by cafehaus** [comment]
我也遇到了，我是用的那个嵌套环形图，目前的解决方案是，把数据用两个字段存起来，一个原始数据（绘制数据说明用），一个用来控制进度的数据（渲染图表），当进度为0是强制修改成0.000001，在图上也看不出来差别，内圆的背景色就不会出现了
