### ISSUE TITLE
拆线图的Y轴度量需要弄成百分比的形式，请问有没有formatter相关的示例？

### ISSUE THREAD

**Issue by yanhan569046480** [antvis/wx-f2#42]
@simaQ

**Comment by yanhan569046480** [comment]
不用了，已经知道了
![image](https://user-images.githubusercontent.com/1505382/42556790-5649fb08-851f-11e8-81d3-30afc947b2c4.png)

**Comment by ye1641893401** [comment]
这个在微型小程序 不能展示百分号

**Comment by ye1641893401** [comment]
H5可以大佬有什么解决方案吗
