### ISSUE TITLE
wx-F2怎么进行重绘？

### ISSUE THREAD

**Issue by yaotaiye** [antvis/wx-f2#45]
比如我按时间请求接口，刷新图表里面的文本、图形以及交互事件都要改变。  chart.changeData(xxx);只是改变图形，文本并没有被清空，交互事件再点点击会报错。

**Comment by simaQ** [comment]
参考这个 demo:https://antv.alipay.com/zh-cn/f2/3.x/demo/pie/pie-with-label.html

changeData 之后，还需要重新绘制文本：

![image](https://user-images.githubusercontent.com/6628666/42755278-18c56ea2-892a-11e8-9ffb-68e7222a3cc4.png)
