### ISSUE TITLE
柱状图x轴显示

### ISSUE THREAD

**Issue by secularworld** [antvis/wx-f2#46]
![image](https://user-images.githubusercontent.com/40487542/42747686-fd2047ae-890f-11e8-9a8c-b7ae76bec4b6.png)

有没有办法让X轴的文字垂直显示？

**Comment by simaQ** [comment]
可以的，参考这个 demo:  https://antv.alipay.com/zh-cn/f2/3.x/demo/axis/rotate.html

设置 rotate 属性（需要使用弧度制）即可：

```js
// 坐标轴文本旋转
chart.axis('Year', {
  label: {
    rotate: -Math.PI / 2, // 设置旋转角度
    textAlign: 'end',
    textBaseline: 'middle'
  }
});
```
