### ISSUE TITLE
图表更新显示bug

### ISSUE THREAD

**Issue by secularworld** [antvis/wx-f2#49]
在微信小程序中，如果更新数据过快并且图标初始化还没完成，会报错（Cannot read property 'changeData' of null）或者不显示，有什么处理办法没有？

**Comment by jxzlhy** [comment]
我也遇到了，不知道怎么弄

**Comment by simaQ** [comment]
判断一下，在确保数据加载进来后再绘制图表。

至于 "Cannot read property 'changeData' of null" 这个报错，是 chart 对象还没有生成导致的。也可以通过预防性的代码解决， `chart && chart.changeData(put your data)`

**Comment by secularworld** [comment]
@jxzlhy  我现在这样处理

          var charUpdateName;
          var chartUpdate=function(){
            if (chart != null) {
              console.log("---")
              setting(_channelSoldList1)
              chart.changeData(_channelSoldList1)
              clearInterval(charUpdateName)
            }
          }
          charUpdateName = setInterval(chartUpdate, 100);

**Comment by secularworld** [comment]
@simaQ 怎么去掉饼图的动画啊，更新数据的时候老是由大变小
（   chart.interval().animate(false)  好像没用    ）

**Comment by secularworld** [comment]
@simaQ 自定义tooltip怎么放在底部

**Comment by simaQ** [comment]
目前你可以通过设置 offsetY 属性将 tooltip 调整至底部

```js
chart.tooltip({
  offsetY: {Number}
});
```

**Comment by secularworld** [comment]
加载动画该怎么去掉啊

**Comment by simaQ** [comment]
chart.animate(false)

**Comment by secularworld** [comment]
offsetY 属性好像对自定义的tooltip没用

chart.tooltip({
    custom: true, // 自定义 tooltip 内容框

    offsetY: 100,
    onChange(obj) {
      const legend = chart.get('legendController').legends.top[0];
      const tooltipItems = obj.items;
      const legendItems = legend.items;
      const map = {};
      legendItems.map(item => {
        map[item.name] = Object.assign({}, item);
      });
      tooltipItems.map(item => {
        const { name, value } = item;
        if (map[name]) {
          map[name].value = value;
        }
      });
      legend.setItems(Object.values(map));
    },
    onHide() {
      const legend = chart.get('legendController').legends.top[0];
      legend.setItems(chart.getLegendItems().country);
    }
  });

**Comment by simaQ** [comment]
哦，你是 tooltip 和 legend 结合使用的例子。这种情况，先配置 legend，将其显示在底部，然后改下自定义 tooltip 的部分代码即可：

```js
chart.legend({
  position: 'bottom'
});
chart.tooltip({
  onChange(obj) {
    const legend = chart.get('legendController').legends.bottom[0]; // 取 bottom 的图例对象
    const tooltipItems = obj.items;
    const legendItems = legend.items;
    const map = {};
    legendItems.map(item => {
      map[item.name] = Object.assign({}, item);
    });
    tooltipItems.map(item => {
      const { name, value } = item;
      if (map[name]) {
        map[name].value = value;
      }
    });
    legend.setItems(Object.values(map));
  },
  onHide() {
    const legend = chart.get('legendController').legends.bottom[0]; // 取 bottom 的图例对象
    legend.setItems(chart.getLegendItems().country);
  } 
});
```

**Comment by secularworld** [comment]
嗯嗯，可以了，多谢

**Comment by secularworld** [comment]
更新数据的时候如果设置了chart.changeSize()，形成的由大到小的动画怎么去掉

**Comment by simaQ** [comment]
https://antv.alipay.com/zh-cn/f2/3.x/api/animation.html#_chart.animate-

**Comment by secularworld** [comment]
没用
 
 onShow(){
    var char2UpdateName;
    var i=0;
    var chart2Update = function () {
      if (chart != null) {
        i++;
        const data = [
          { type: '饮食', cost: 1+i, a: '1' },
          { type: '服饰美容', cost: 2+2*i, a: '1' },
          { type: '健康', cost: 3, a: '1' },
          { type: '生活用品', cost: 2 + i, a: '1' },
          { type: '其他', cost: 14.9, a: '1' },
          { type: '交通出行', cost: 8.7, a: '1' }
        ]; chart.changeSize(null, 400)
        chart.animate(false)
        chart.changeData(data)
      }
    }
    char2UpdateName = setInterval(chart2Update, 1000);
  }

**Comment by secularworld** [comment]
legend和tooltip在一起用会到处Cannot read property '0' of undefined（chart2.get('legendController').legends.top[0]）

**Comment by jxzlhy** [comment]
可以啊，老哥

**Comment by simaQ** [comment]
![image](https://user-images.githubusercontent.com/6628666/42990778-46d93b52-8c36-11e8-8df8-1647ed129697.png)

我已经在回复里面详细得给出说明了。。。

![image](https://user-images.githubusercontent.com/6628666/42990803-56eb1af6-8c36-11e8-8864-61fe2b13b1a8.png)
