### ISSUE TITLE
雷达图，配置label显示颜色无效

### ISSUE THREAD

**Issue by xuetian120** [antvis/wx-f2#52]
chart.axis('name', {
    grid: {
      lineDash: null
    },
    label: {
      Offset: 10,
      textStyle: {
        fill: '#ff0000',
        textAlign: 'center' // 设置坐标轴 label 的文本对齐方向
      }
    }
  });

**Comment by xuetian120** [comment]
textStyle无论如何设置都无效

请问是否有方法自定义坐标文本的颜色？

**Comment by simaQ** [comment]
F2 的接口和 G2 接口不同，不支持 textStyle, 具体设置方式已经在 #53 回答了。

微信小程序上的图表使用方式和 H5 是一样的，可以多看看官网的 demo:https://antv.alipay.com/zh-cn/f2/3.x/demo/index.html

**Comment by simaQ** [comment]
不客气~
