### ISSUE TITLE
坐标轴上的提示文本的颜色怎么定义？

### ISSUE THREAD

**Issue by xuetian120** [antvis/wx-f2#53]
坐标轴上的提示文本的颜色怎么定义，默认是灰色的，如何自定义成别的颜色跟大小？

**Comment by simaQ** [comment]
请问你指的是图中蓝色区域的坐标轴文本么？

![image](https://user-images.githubusercontent.com/6628666/43361802-e96af45a-930c-11e8-9c76-87c930b0e419.png)


可以参考 API ：https://antv.alipay.com/zh-cn/f2/3.x/api/axis.html
坐标轴文本的颜色，直接通过配置 label 属性即可

```js
chart.axis('坐标轴对应的数据字段名', {
  label: {
    fill: 'red'
  }
});
```
