### ISSUE TITLE
怎么通过api接口返回数据回来后再渲染图表

### ISSUE THREAD

**Issue by xuetian120** [antvis/wx-f2#54]
示例都是假设一进去页面，数据都存在，直接在data中赋值渲染。现实通过接口返回图表数据后，通过this.setDat({
opts: {
onInit: initChart
}
})
却无效，没有显示出图表???
希望有示例说明一下，谢谢！

**Comment by simaQ** [comment]
可以参考这个示例： https://github.com/antvis/wx-f2/tree/master/pages/charts/k，延迟加载 lazyLoad 和异步请求的例子。

**Comment by konanzheng** [comment]
参考例子失效了@simaQ

**Comment by xcmg** [comment]
问题解决没？

**Comment by sugusGit** [comment]
参考的主动触发例子的完整链接在这里https://github.com/antvis/wx-f2/blob/master/pages/charts/k/index.js
