### ISSUE TITLE
[微信小程序]请问如何修改 雷达图 字体的颜色

### ISSUE THREAD

**Issue by 376924098** [antvis/wx-f2#55]
如 修改 小程序 示例 雷达图 选证择时能力  绝对收益能力 等这些文字的颜色

**Comment by simaQ** [comment]
如下，设置下 label 属性就可以了，这个属于坐标轴文本的配置，可以参见 [Axis API](https://antv.alipay.com/zh-cn/f2/3.x/api/axis.html)
```js
chart.axis('name', {
    grid: {
      lineDash: null
    },
    label: {
      fill: 'red'
    }
});
```
