### ISSUE TITLE
柱状图怎么自定义成这种shape呢

### ISSUE THREAD

**Issue by dcharlie123** [antvis/wx-f2#56]
[自定义shape](http://om10n1h33.bkt.clouddn.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180730114940.png)

**Comment by simaQ** [comment]
emmm.... 这个要是在 H5 环境，直接使用 chart.guide().html() 即可，但是在小程序环境就比较难办了。目前没有支持这个 feature, 因为通过自定义 shape 的话，有两种方法：

1.  自己绘制笑脸的 path (这个成本蛮高的。。。)
2. 使用 image，目前还没有兼容小程序的 image 接口

**Comment by dxq613** [comment]
小程序不知道是否支持 iconfont ,如果支持的话直接参考：https://www.yuque.com/antv/blog/wix2gd
