### ISSUE TITLE
怎么在自定义组件里放图表呢

### ISSUE THREAD

**Issue by sticks0613** [antvis/wx-f2#57]
在项目刚打开的时候会报错：
An SelectorQuery call is ignored because no proper page or component is found. Please considering using `SelectorQuery.in` to specify a proper one.

**Comment by iWtbAbh** [comment]
我用mpvue，想跑下这个项目里的pages的例子。
init方法里的：
const query = wx.createSelectorQuery().in(this) 
（这么用导致出现上面那种情况）
const query = wx.createSelectorQuery(this.$root.$mp.page)
（这么用会出现图表，但是会报错： “TypeError: Converting circular structure to JSON”）
