### ISSUE TITLE
渐变

### ISSUE THREAD

**Issue by Desever** [antvis/wx-f2#58]
柱体可以改成渐变颜色吗？没有找到类似的api

**Comment by simaQ** [comment]
可以的，目前的技术方案是：使用 canvas 上下文接口创建一个渐变色 gradient 对象，然后使用这个对象即可。

参考 demo:  https://github.com/antvis/wx-f2/blob/master/pages/charts/gradient-column/index.js

![image](https://user-images.githubusercontent.com/6628666/43498204-74f16136-9578-11e8-8ff0-1102a1935372.png)

**Comment by Desever** [comment]
一个cavnas里面有两种类型的图表，一个是bar一个是line，要使用不同的渐变如何处理呢

**Comment by simaQ** [comment]
目前渐变色是对全局生效的，目前还不支持两种不同的渐变色设置。。

**Comment by Desever** [comment]
好的谢谢

**Comment by simaQ** [comment]
不客气，这块我考虑支持下
