### ISSUE TITLE
canvas大小发生变化后已经绘制的图表大小可以自适应的变化吗

### ISSUE THREAD

**Issue by ll929** [antvis/wx-f2#59]
canvas大小发生变化后已经绘制的图表大小可以自适应的变化吗

**Comment by simaQ** [comment]
目前不支持自适应，但是你可以通过调用 [chart.changeSize(width, height)](https://antv.alipay.com/zh-cn/f2/3.x/api/chart.html#_changeSize)  接口达到效果
