### ISSUE TITLE
柱状图标注显示不下问题

### ISSUE THREAD

**Issue by secularworld** [antvis/wx-f2#60]
使用自定义tooltip，当点击柱状图后数据过长，显示不下，怎么处理

![image](https://user-images.githubusercontent.com/40487542/43629953-5f7c7e48-9731-11e8-960d-5ca4975db19f.png)

![image](https://user-images.githubusercontent.com/40487542/43629939-59ab1952-9731-11e8-9ab1-a4b90d2861d3.png)

**Comment by simaQ** [comment]
恩，你可以在 chart.legend() 接口那里定义下 itemWidth，将每个图例项的宽度写死，这样 tooltip 触发的时候就不会超出了。

```js
chart.legend({
  itemWidth: 150 // 这个值你可以根据自己的情况调整下
});
```
