### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by secularworld** [antvis/wx-f2#61]
在js添加交互功能后，感觉使用chart.changeData()之后，图表不太稳定，有时候不显示也不报错，有时候显示了，点击交互图表没反应

**Comment by simaQ** [comment]
有可复现的例子么？

**Comment by secularworld** [comment]
暂时找不出，主要是有时候有问题，有时候又没问题，但是不报错

**Comment by secularworld** [comment]
更新数据的时候有没有时限？是不是多久之后就不进行绘制了

**Comment by simaQ** [comment]
更新数据是没有什么时限的。

**Comment by secularworld** [comment]
要不我把部分代码发给你，帮忙看看？

**Comment by simaQ** [comment]
恩，包含数据和可运行的代码，最好在截个图~

**Comment by secularworld** [comment]
链接：https://pan.baidu.com/s/1yCmBDZ7p-8Jo8wjGKxZo6Q 密码：5v6e

进入主界面，选择经营中心,在点击首页，来回点击多重复几次就出现了
进入主界面，选择经营中心--》节假日分析--》腊八节，多进几次就好出现不绘制的现象



![image](https://user-images.githubusercontent.com/40487542/43873459-3740f18e-9bb9-11e8-9e1f-64588888099b.png)

**Comment by simaQ** [comment]
在微信开发者工具打开不能进入经营中心。。

**Comment by secularworld** [comment]
为什么啊，报错了吗

**Comment by simaQ** [comment]
导入项目时生成的 appid，提示我不是项目的开发者。我用测试的 appid，页面就提示
![image](https://user-images.githubusercontent.com/6628666/43875511-4070de36-9bc3-11e8-9c76-3c9849f570a4.png)

url 权限问题.....

---

另外图表不绘制的时候，有没有什么报错信息？

**Comment by secularworld** [comment]
不登录开发者工具看看，直接使用

**Comment by simaQ** [comment]
1. 你更新下 f2-canvas 组件 https://github.com/antvis/wx-f2/tree/master/f2-canvas ，现在已经将小程序的交互和 H5 的交互统一了
2. 把 chart 的动画关闭试下

```js
chart = new F2.Chart({
    el: canvas,
    width: width * 0.92,
    height:350,
    animate: false // 关闭动画
  });
```

**Comment by secularworld** [comment]
嗯嗯，多谢

**Comment by secularworld** [comment]
还是有问题，没有解决o(╯□╰)o

**Comment by simaQ** [comment]
有没有报错信息？ 我是在 IDE 上操作的，没有没有复现...

**Comment by secularworld** [comment]
没有报错，就是不显示，多试几次应该就会出现吧，我这里出现的很频繁

**Comment by simaQ** [comment]
恩恩，在这里 https://unpkg.com/@antv/f2@3.2.0-beta.16/build/f2-all.js 

Github 地址：https://github.com/antvis/f2

**Comment by secularworld** [comment]
好像找到问题了，好像是我们申明的chart变量，是在page外面申明的，我自己感觉在page外面申明的变量不会随着页面卸载onUnLoad而消失，当这个页面再次重新加载的时候onLoad，chart变量是有值的（之前实例化过，没有随页面销毁而销毁），所以会直接更新，但是页面本身又会重新创建一个chart变量，导致之前的更新无效，图表无显示

**Comment by simaQ** [comment]
搜噶，那如果是这个问题的话，那应该好解决的

**Comment by secularworld** [comment]
嗯嗯，我在onUnLoad方法里面主动赋值null，先试试，目前没遇到问题

**Comment by simaQ** [comment]
恩，或者可以在创建 chart 的代码逻辑块，先判断下 chart 是否存在，存在的话直接 chart.destroy() 掉重新绘制。或者 chart.clear() 掉，这样就不用重新创建chart 实例

**Comment by secularworld** [comment]
这样好像不行，首先下面的changeDate可能会先执行，所以不能销毁chart，然后刚刚我试了如果在初始化chart的时候判断chart!=null就不就行重新创建，直接使用原来的chart也不会进行绘制，必须用新初始化的chart

**Comment by simaQ** [comment]
> 嗯嗯，我在onUnLoad方法里面主动赋值null，先试试，目前没遇到问题

那使用你刚才提到的方法可行吗

**Comment by secularworld** [comment]
暂时还在测试，应该是可行的，就是性能不高，有待优化

**Comment by yumengbdw** [comment]
> > 嗯嗯，我在onUnLoad方法里面主动赋值null，先试试，目前没遇到问题
> 
> 那使用你刚才提到的方法可行吗
我这边也碰到了赋值null也是无效,就是三个tab每个tab下两张图,切换后不报错,不显示
