### ISSUE TITLE
图表显示空白

### ISSUE THREAD

**Issue by sticks0613** [antvis/wx-f2#62]
项目打开时，第一个页面含有图表，图表不显示，出现如下警告：
An SelectorQuery call is ignored because no proper page or component is found. Please considering using `SelectorQuery.in` to specify a proper one.

重新编译一下就可以出现了，不知道什么问题，试了下官方示例若打开项目第一个页面有图表也会出现这种问题

**Comment by simaQ** [comment]
应该是生命周期的问题吧，图表需要在页面上的 canvas 元素渲染完成之后再初始化
