### ISSUE TITLE
分组柱状图和折线图叠加！！！

### ISSUE THREAD

**Issue by sticks0613** [antvis/wx-f2#64]
分组的数据格式是这样的：
var data = [{
  name: 'London',
  time: '周一',
  rain: 18.9
}, {
  name: 'London',
  time: '周二',
  rain: 28.8
}, {
  name: 'London',
  time: '周三',
  rain: 39.3
}, {
  name: 'Berlin',
  time: '周一',
  rain: 12.4
}, {
  name: 'Berlin',
  time: '周一',
  rain: 23.2
}, {
  name: 'Berlin',
  time: '周三',
  rain: 34.5
}];

一个柱状和折线叠加数据格式是这样的：
var data = [{
  time: '周一',
  tem: 6.9,
  rain: 10
}, {
  time: '周二',
  tem: 9.5,
  rain: 13
}, {
  time: '周三',
  tem: 14.5,
  rain: 14
}];

怎么把这两种数据格式融合，显示分组柱状图和折线图叠加的!!!

**Comment by simaQ** [comment]
不要着急，不要着急，参考这个 demo 的数据格式： https://codepen.io/Sima/pen/OwaEZN

**Comment by sticks0613** [comment]
好的，谢谢小姐姐

**Comment by simaQ** [comment]
给每一个分组定义之后，需要给其他的分组也同样定义一份才行

![image](https://user-images.githubusercontent.com/6628666/43882667-13d9c73c-9be3-11e8-90a1-c0560589686c.png)

**Comment by sticks0613** [comment]
懂了
