### ISSUE TITLE
有没有延迟加载啊？

### ISSUE THREAD

**Issue by 342688695** [antvis/wx-f2#7]
想从后台返回数据在加载图表？

**Comment by simaQ** [comment]
有的，参考下这个例子 https://github.com/antvis/wx-f2/tree/master/pages/charts/k

**Comment by 342688695** [comment]
小程序多个图表在安卓机上有些卡顿，这是怎么回事呢

**Comment by linzhanhong** [comment]
后台返回数据加载图表，控制台报错: Cannot read property 'init' of null，为什么呀？

**Comment by imBigbaibai** [comment]
同问楼上，init这个方法在哪呢？

**Comment by tu6ge** [comment]
案例链接找不到了
