### ISSUE TITLE
如何在onLoad的时候手动初始化图表呢

### ISSUE THREAD

**Issue by PeterPuffer** [antvis/wx-f2#70]
在onLoad的时候会获取数据，数据获取之后会填充到图表的data中，但是报了一个错误.
![image](https://user-images.githubusercontent.com/28674080/44077918-be92f3ea-9fd7-11e8-83b5-04a3614fe61d.png)

**Comment by simaQ** [comment]
是不是 chart 对象为空？

**Comment by PeterPuffer** [comment]
嗯嗯对

**Comment by simaQ** [comment]
你是怎么写的呢？ 你需要保证 chart 对象创建了之后才能调用 chart.changeData()

**Comment by PeterPuffer** [comment]
我在page的外面写的init, 在page的data中写了{opt:initChart} 按照例子来的，
![image](https://user-images.githubusercontent.com/28674080/44082837-f19aee7a-9fe4-11e8-9ffe-dc96f5ed4f84.png)

![image](https://user-images.githubusercontent.com/28674080/44082699-93004914-9fe4-11e8-93c6-a8308ebb327b.png)

**Comment by PeterPuffer** [comment]
有什么办法可以让chart在onload 中不为空吗
