### ISSUE TITLE
能为横轴和纵轴添加标签吗？

### ISSUE THREAD

**Issue by swallowsonny** [antvis/wx-f2#71]
通过标签表达横轴与纵轴各代表的含义

**Comment by simaQ** [comment]
恩呢，可以的，这个可以通过 chart.guide().text({}) 来实现。

参见 demo:  https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/negative-column-1.html

![image](https://user-images.githubusercontent.com/6628666/44127751-6cc471e8-a071-11e8-8cf5-da1995dd8691.png)

**Comment by swallowsonny** [comment]
@simaQ 谢谢，这个好像只有Y轴的，有没有X轴的？

**Comment by simaQ** [comment]
https://codepen.io/Sima/pen/Yjbqer  参照这个 demo, 用法一样的，改下 position 就好了，api 在这里 https://antv.alipay.com/zh-cn/f2/3.x/api/guide.html#_Text
