### ISSUE TITLE
你好，本人小白一枚 请教个问题 急！！！

### ISSUE THREAD

**Issue by PeterPuffer** [antvis/wx-f2#72]
我按照readme的例子写了一个柱形图，想修改为在onLoad方法中通过wx.request获取数据, 之后使用changeData 将图表数据更新(图表data默认是[] ) 但是在写的过程中，总是报一个错误，这个错误是由于没有初始化chart导致的。 但是我想了很多办法，都没有办法在页面加载出来之后显示通过接口获取到的数据，请问这种情况有什么办法吗，感谢感谢。

**Comment by simaQ** [comment]
好的，我研究一下

**Comment by simaQ** [comment]
为什么不直接在 onLoad 方法中通过wx.request获取数据之后，就直接绘制 chart ?  你可以直接参考下这个 demo： https://github.com/antvis/wx-f2/tree/master/pages/charts/k，你看下是否满足你的需要：

![image](https://user-images.githubusercontent.com/6628666/44152253-a085816e-a0d7-11e8-8285-7496193f21c6.png)
