### ISSUE TITLE
环形内部问题更新问题

### ISSUE THREAD

**Issue by secularworld** [antvis/wx-f2#73]
设置值后有什么更新，有时候不更新是什么问题啊

chart.guide().clear();
chart.guide().text({
      position: ['50%', '50%'],
      content: numberToMoney(sum) + danwei,
      style: {
        fontSize: 14
      }
    });

**Comment by secularworld** [comment]
@simaQ 这个问题应该怎么解决啊

**Comment by dxq613** [comment]
调用一下 chart.repaint()

**Comment by secularworld** [comment]
嗯嗯，多谢
