### ISSUE TITLE
x轴文本显示

### ISSUE THREAD

**Issue by sticks0613** [antvis/wx-f2#74]
x轴文本太长， 导致图表是这样的
<img width="351" alt="2018-08-20 1 15 39" src="https://user-images.githubusercontent.com/32888772/44321535-28f6dd80-a47b-11e8-8f27-136eee9a208c.png">

让文本旋转，还是显示不全
<img width="341" alt="2018-08-20 1 15 28" src="https://user-images.githubusercontent.com/32888772/44321548-3ca24400-a47b-11e8-8db1-9261143b3f5f.png">

怎么能完全显示，或者x轴只显示几个文本，不全部显示

**Comment by simaQ** [comment]
在列定义里面设置 tickCount, 参加 demo https://antv.alipay.com/zh-cn/f2/3.x/demo/line/basic.html

**Comment by sticks0613** [comment]
我设置了3个，只有两个
<img width="342" alt="2018-08-20 2 39 59" src="https://user-images.githubusercontent.com/32888772/44324122-2bf7cb00-a487-11e8-85e5-93f8d9374590.png">

**Comment by sticks0613** [comment]
数据不是连续的时间

<img width="647" alt="2018-08-20 2 48 16" src="https://user-images.githubusercontent.com/32888772/44324384-18009900-a488-11e8-8f35-37fd1d63cf13.png">

**Comment by simaQ** [comment]
更新下 f2-canvas/lib/ 下的 f2.js: https://github.com/antvis/wx-f2/blob/master/f2-canvas/lib/f2.js
