### ISSUE TITLE
请问pieselect中如何修改提示文字大小，图表颜色如何随机呢

### ISSUE THREAD

**Issue by PeterPuffer** [antvis/wx-f2#75]
小姐姐你好，我在pieselect这个demo中想修改字体的大小, 如下图红色框内所示
![image](https://user-images.githubusercontent.com/28674080/44322252-0f579500-a47f-11e8-9bf8-f781e472a269.png)

在js文件内加入fontSize代码后，并没有发现字体有变化
![image](https://user-images.githubusercontent.com/28674080/44322279-2f875400-a47f-11e8-8489-3a559c41ae12.png)

#39 这个问题我也看了 但是不太懂该如何去修改，貌似是自己绘图的时候才会用到类似的写法

请教下小姐姐如何修改字体大小，另外我看到color是写死的，能否随机颜色呢
![image](https://user-images.githubusercontent.com/28674080/44322339-79703a00-a47f-11e8-92db-890132b79929.png)

**Comment by simaQ** [comment]
###  Issue 1. 修改字体大小
这个是属于图例的文本样式设置，需要在 chart.legend() 这个接口上配置, 参见 api: https://antv.alipay.com/zh-cn/f2/3.x/api/legend.html#_chart.legend-field,-config- 

```js
chart.legend({
  nameStyle: {
    fontSize: 12
  }
});
```

### Issue 2: 颜色是否可以随机

可以，将颜色数组删除，直接定义  `.color('name')` 即可

**Comment by simaQ** [comment]
PS:  按照 issue 模板提问，一个问题一个 issue.

**Comment by PeterPuffer** [comment]
感谢小姐姐的耐心回答。 下次会按照模版提问的 [cute]
