### ISSUE TITLE
tooltip显示

### ISSUE THREAD

**Issue by sticks0613** [antvis/wx-f2#78]
怎么使这个tooltip有x轴的时间

<img width="337" alt="2018-08-20 4 03 24" src="https://user-images.githubusercontent.com/32888772/44327920-aaa63580-a492-11e8-997a-fdc23adc9378.png">

**Comment by simaQ** [comment]
https://antv.alipay.com/zh-cn/f2/3.x/api/tooltip.html#_API 
 showTitle 自己先找下 api
