### ISSUE TITLE
[微信小程序]请问如何修改 雷达图 加载的数据

### ISSUE THREAD

**Issue by 376924098** [antvis/wx-f2#79]
按照  readme ：https://github.com/antvis/wx-f2/blob/master/README.md 里的方式
定义全局变量
let chart = null;
initChart 方法里 进行实例化
chart = new F2.Chart({
    el: canvas,
    width,
    height
  });

但是我在其他function 里 拿到的 chart 是null
如果 要修改 已经加载的数据的话 是不应该再调用  
chart.source(data, {
    sales: {
      tickCount: 5
    }
  });

chart.render();

**Comment by sven0726** [comment]
me too

**Comment by FreeRide-Joe** [comment]
改变数据的方法是 `chart.changeData(data)`，文档有写。
另外在使用chart前要确保chart已经初始化，不能确定的时候使用可以先判断一下chart是否被初始化。
