### ISSUE TITLE
模板推送页面的图表位置定位错误

### ISSUE THREAD

**Issue by lishaoh** [antvis/wx-f2#86]
![wechatimg2695](https://user-images.githubusercontent.com/20917295/44943694-5c335800-adfd-11e8-93d0-064bea25c7df.jpeg)

* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
你好，可以看下是否是样式定位导致的
