### ISSUE TITLE
小程序中项目中，将图表导出图片

### ISSUE THREAD

**Issue by misszoessmile** [antvis/wx-f2#92]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

希望能提供的能力：
小程序中项目中，将图表导出图片。

**Comment by aloneszjl** [comment]
用这个可以直接导出 https://developers.weixin.qq.com/miniprogram/dev/api/canvas/wx.canvasToTempFilePath.html

**Comment by misszoessmile** [comment]
@aloneszjl 试过了，报错："canvasToTempFilePath: fail canvas is empty"。
我的需求是这样，同一个页面有4个图表，然后页面头部有一个生成报告按钮，点击生成报告按钮要拿到4个图表的图片。
如图：
![image](https://user-images.githubusercontent.com/35720631/45465741-0dfd4d80-b749-11e8-8120-d4a8065de2ea.png)

**Comment by aloneszjl** [comment]
canvasToTempFilePath的第二个参数你有传吗，最好贴下代码出来，不然很难帮你找问题

**Comment by ywyhero** [comment]
> canvasToTempFilePath的第二个参数你有传吗，最好贴下代码出来，不然很难帮你找问题

![image](https://user-images.githubusercontent.com/16243686/45486892-432c8e80-b78f-11e8-8e0f-1bcb68b23766.png)
![image](https://user-images.githubusercontent.com/16243686/45486901-4c1d6000-b78f-11e8-965e-54a70950694e.png)

**Comment by aloneszjl** [comment]
你试试传第二个参数进去

**Comment by misszoessmile** [comment]
解决了，谢谢！

**Comment by ywyhero** [comment]
> 解决了，谢谢！
可以告知下如何解决的吗？

**Comment by misszoessmile** [comment]
> > 解决了，谢谢！
> > 可以告知下如何解决的吗？

参考了echarts-for-weixin，在f2-canvas.js的methods中加入以下代码：
canvasToTempFilePath(opt) {
      this.canvas.ctx.draw(true, setTimeout(() => {
        wx.canvasToTempFilePath(Object.assign(opt, this.data), this);
      }, 100));
    },
调用时：
js:
const component = that.selectComponent('#ecComponent1');
        component.canvasToTempFilePath({
          success: res => {
            paths.push(res.tempFilePath);
            console.log(1)
            resolve();
          }, fail: res => {
            that.setData({
              reportBtn: false
            });
          },
        });
wxml:
<view class="container">
          <ff-canvas id="ecComponent1" canvas-id="ecComponent1" opts="{{ opts1 }}"> </ff-canvas>
        </view>
