### ISSUE TITLE
如何修改legend value 的颜色

### ISSUE THREAD

**Issue by aloneszjl** [antvis/wx-f2#94]
我看文档都是统一设置的
```
valueStyle: {
  textAlign: 'center', // 文本对齐方向，可取值为： start middle end
  fill: '#404040', // 文本的颜色
  fontSize: '12', // 文本大小
  fontWeight: 'bold', // 文本粗细
  textBaseline: 'top' // 文本基准线，可取 top middle bottom，默认为middle
}
```
但是我想针对不同的值给不同的颜色，怎么做？例如折线图，有两条线，其中一条的legend是大于0的，想用红色，另外一条是小于0，想用绿色

**Comment by simaQ** [comment]
这个功能不支持哦

**Comment by aloneszjl** [comment]
有其他方法 实现吗？我觉得这个功能挺常用的。

**Comment by simaQ** [comment]
这个目前在小程序端真的没有什么办法

**Comment by aloneszjl** [comment]
ok，那就只能用小程序写一个自定义的，不用这个库里面的legend了，谢谢你。

**Comment by simaQ** [comment]
恩，不客气，对于自定义图例来说，我们提供了 chart.getLegendItems() 接口，用于获取图例的 items 信息。https://antv.alipay.com/zh-cn/f2/3.x/api/chart.html#_getLegendItems
