### ISSUE TITLE
scale问题

### ISSUE THREAD

**Issue by sticks0613** [antvis/wx-f2#95]
![d93cb1f61423b90757d47b354f3d10d](https://user-images.githubusercontent.com/32888772/45350825-4ab13380-b5e7-11e8-94d0-d168add24af0.png)

我如果 chart.scale 想用chart.axis里面label后面函数的text，但是label后面函数是异步的，这个应该怎么解决呢

**Comment by simaQ** [comment]
```js
chart.scale('现金流净额', {
  min: -20000000000,
  max: 40000000000,
  formatter(val) {
    return parseFloat(val).toFixed(2) / 100000000 + '亿';
  }
})

```

**Comment by sticks0613** [comment]
不是这个意思，是因为想判断 value这边坐标轴的最大值和最小值，然后给 '现金流净额' 的坐标轴设置成一样的

**Comment by simaQ** [comment]
我真的很难明白你的意思，不知道你是不是想表达坐标轴的文本只展示 min 和 max 这两个数值，但是需要格式化之后的？如果是这个意思，你直接设置 ticks 就好了

```js
chart.scale('现金流净额', {
  min: -20000000000,
  max: 40000000000,
  ticks: [ -20000000000, 40000000000  ] 
})
```

**Comment by sticks0613** [comment]
我有两个Y轴，两个单位都是百亿，所以想合并成一个左边，不知道我们这边图表是怎么划分的，两个坐标轴不一样，所以我需要把右边的坐标轴，区间设置成左边一样的，但是我这个图的数据是动态的，我怎么获取动态的min,max，然后给右边的坐标轴设置成一样的区间

**Comment by sticks0613** [comment]
好的，下次一定，谢谢啦
