### ISSUE TITLE
还是关于真机浮动问题

### ISSUE THREAD

**Issue by iceSnowChen** [antvis/wx-f2#96]
![image](https://user-images.githubusercontent.com/37735658/45401042-7da80580-b681-11e8-9507-9e0768e90e7f.png)
![image](https://user-images.githubusercontent.com/37735658/45401138-cfe92680-b681-11e8-8438-b6b8ecdc5ac9.png)

![image](https://user-images.githubusercontent.com/37735658/45401210-2bb3af80-b682-11e8-836f-b1d3960decd0.png)
问一下，有人知道这个该怎么设置吗

**Comment by misszoessmile** [comment]
cover-view

**Comment by misszoessmile** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/cover-view.html

**Comment by iceSnowChen** [comment]
> 盖视

真的可以，感谢这位小伙。
