### ISSUE TITLE
饼图，数据全部为0时显示异常

### ISSUE THREAD

**Issue by misszoessmile** [antvis/wx-f2#98]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

全部为0时显示如下：
![image](https://user-images.githubusercontent.com/35720631/45409649-61689080-b6a2-11e8-9341-354558f8eece.png)

**Comment by aloneszjl** [comment]
@simaQ 暂无数据时是需要自己处理的吗？有没有相关的ui显示暂无数据的？

**Comment by simaQ** [comment]
@aloneszjl 不要搭车提问，建议另开一个 issue

**Comment by simaQ** [comment]
... 数据如果全部为 0 的话表示饼图的每个扇形面积、夹角都为 0，自然就不会绘制了... 这不是异常。

这里你应该自己判断一下，如果数据全为 0 的话，显示一个文案提示下。

**Comment by misszoessmile** [comment]
> ... 数据如果全部为 0 的话表示饼图的每个扇形面积、夹角都为 0，自然就不会绘制了... 这不是异常。
> 
> 这里你应该自己判断一下，如果数据全为 0 的话，显示一个文案提示下。

好的，谢谢！
