### ISSUE TITLE
坐标轴问题

### ISSUE THREAD

**Issue by sticks0613** [antvis/wx-f2#99]
左边坐标轴是柱状图的，右边坐标轴是两条折线的，但是两条折线的的区间不同，但也相差不大

<img width="371" alt="2018-09-13 4 00 45" src="https://user-images.githubusercontent.com/32888772/45475295-7b6fa500-b76e-11e8-8ea5-7f109e981427.png">

如果加上 syncY: true, 会出现下面这种情况

<img width="347" alt="2018-09-13 4 11 35" src="https://user-images.githubusercontent.com/32888772/45475710-c1793880-b76f-11e8-8ba6-fa2a6d075b7d.png">

**Comment by sticks0613** [comment]
应该怎么实现呢

**Comment by simaQ** [comment]
你这个数值差这么多，怎么可能通过 sync 来统一数据的范围？这个变量是用来统一全部Y轴字段数据的范围的。你这种情况。你直接在 chart.source 方法中给两条折线图的Y轴字段设置下相同的 min 和 max 就可以了
